### ISSUE TITLE
Homebridge shows update to 1.8.35, but 1.7 still installing 

### ISSUE THREAD

**Issue by rhuss2** [grzegorz914/homebridge-lgwebos-tv#104]
Homebridge shows a update is available to 1.8.35, but when you attempt to install it, 1.7 is installed.

**Comment by seabrawk** [comment]
It is installing the correct npm package, only the release notes/changelog aren't being maintained; still worth a check.

**Comment by gdotp01** [comment]
I think I have the same issue. It says it needs to update to 1.7 but is already on a later version.
![9B869C85-AC25-4026-B9D9-431F3FF8D611](https://user-images.githubusercontent.com/50060482/131221457-0999efe6-373d-4253-82ac-faf1fd45049a.jpeg)
![751FC304-B241-44FF-BE78-AEEB4E24E396](https://user-images.githubusercontent.com/50060482/131221459-c303a211-dd6d-43a9-baaf-18ac36c97f38.jpeg)

**Comment by grzegorz914** [comment]
Release notes have nothing to do with app version. Just update and have fan.
