### ISSUE TITLE
Update does not stick

### ISSUE THREAD

**Issue by gdotp01** [grzegorz914/homebridge-lgwebos-tv#107]
This has been an issue for a few months now. The plugin says it needs to update, I update it and 24 hours later it’s asking for the same update to be applied.

**Comment by grzegorz914** [comment]
Uninstall and install again

**Comment by grzegorz914** [comment]
How do You check is installed same version.

**Comment by gdotp01** [comment]
I’m using the homebridge UI. Ive tried again and I’ll see if it sticks this time

**Comment by gdotp01** [comment]
I’m afraid it’s not worked again and is again saying it needs to update. 
![8110CAEF-D524-4915-A6A8-DD343D8F7861](https://user-images.githubusercontent.com/50060482/131543473-0447a2c6-507c-4bef-85a2-f5c4f9456560.png)

**Comment by grzegorz914** [comment]
1.9.0 is latest version, need to be updated

**Comment by gdotp01** [comment]
Ok maybe that is correct today. I can see you updated from 1.7 to 1.9 so I’ll see if this update sticks

**Comment by grzegorz914** [comment]
Its not from 1.7 to 1.9, just the changelog was not updated before. The installed correct version is on Your screenshot.
