### ISSUE TITLE
Is it possible to control volume by voice?

### ISSUE THREAD

**Issue by hsarji** [grzegorz914/homebridge-lgwebos-tv#111]
I installed the plugin successfully. I am able to control the TV's volume from the Home app and from the Control Center using a slider with a lightbulb icon. 

Is there a way to change the volume using Siri? I can ask Siri to turn the TV on/off. But I can't get it to change the volume. Is there a workaround through Shortcuts or something else?

**Comment by hsarji** [comment]
Thank you so much for your reply. I got the brightness slider to change the volume by touching it on the screen. What can I say to Siri so I can change the volume by voice?  I tried renaming the brightness slider to no avail. I've tried, "Hey Siri, turn up volume of TV." "Hey Siri, turn up [name of light." Nothing is working.

**Comment by grzegorz914** [comment]
Hej siri set TV 50%, or Hej Siri increase TV

**Comment by hsarji** [comment]
I tried both statements. I’m getting the following error messages:
![11D48039-826B-4C7D-A9C1-A6603BDD84D2](https://user-images.githubusercontent.com/57333897/136259064-6dfe38dc-626b-4221-b533-c694e1ffcb0e.png)
![6195F076-0148-4FAB-963B-8256F5FE5584](https://user-images.githubusercontent.com/57333897/136259074-29ec0f58-dbf7-473b-8b93-c3b5a325210c.png)
![2C5D1A13-001F-40BA-BAF9-E6E72408BA4F](https://user-images.githubusercontent.com/57333897/136259076-f8f0692f-5186-427c-994d-d818185e739d.png)

**Comment by grzegorz914** [comment]
I close this because no response from user, I thin is solved.
