### ISSUE TITLE
Input list does not reflect Inputs.Name

### ISSUE THREAD

**Issue by eledrich** [grzegorz914/homebridge-lgwebos-tv#114]
Hi,

I've realized yesterday that on the Home app the input selector does not longer show the correct inputs names as defined in the config file (which hasn't changed and is still valid).

Instead I get a list of inputs all labelled after my device's name + a number (e.g. TV, TV 1, TV 2, TV 3, etc.)

I see that behaviour on 1.9.23 and 1.9.24 ; I've tried removing the accessory and adding it back ; same result.

Thanks for your help!

**Comment by grzegorz914** [comment]
update to 1.9.26 and check

**Comment by eledrich** [comment]
Just ran the upddate and restarted Homebridge. Now the TV does not show anymore in the accessory list to be added in the Home app. No config change.

**Comment by eledrich** [comment]
shall I uninstall the plugin and reinstall it ?

**Comment by grzegorz914** [comment]
Why you not backed up your home app config with Controller.app? This is best solution for it.

in other case the behavior is very strange, on my site all working as excepted. The accessory must still in the cashe. Try to reboot iPhone or iPad

**Comment by grzegorz914** [comment]
I close this because no response from user, I thin is solved.
