### ISSUE TITLE
TV shows up as Off when using LG Voice command to turn of the TV screen

### ISSUE THREAD

**Issue by adamxfort** [grzegorz914/homebridge-lgwebos-tv#118]
Just found out that when I use the voice command through LG remote to turn off the TV screen of my LG C9 (I use this when listening to music) the TV shows up as off. I assume that it detects power based on the TV screen, could this be changed? I'm on v1.9.44
Thanks!

**Comment by grzegorz914** [comment]
please update to 45-beta.1, enable debug in plugin settings and get the log after screen off

**Comment by grzegorz914** [comment]
Try 4.5-beta.4 should working correct

**Comment by adamxfort** [comment]
Awesome, it works like a charm now :) Thanks!
