### ISSUE TITLE
Disable brightness (volume) slider

### ISSUE THREAD

**Issue by jonlonergan** [grzegorz914/homebridge-lgwebos-tv#12]
How do I disable the new brightness/volume slider? It’s causing major issues in my configuration. Turning my living room lights to max brightness also turns TV to max volume... I’d rather not have the volume slider as a lightbulb.

Thanks!

**Comment by grzegorz914** [comment]
I will add this Option today leather

**Comment by grzegorz914** [comment]
Option added in latest version.
