### ISSUE TITLE
Arrangement of controls?

### ISSUE THREAD

**Issue by jscribbles** [grzegorz914/homebridge-lgwebos-tv#120]
Is it possible to manage the arrangement of the controls in this Homekit setup?

Basically, I love how clean and functional it is with the simple set up of the power button plus the input menu. That's all I need from the stand point of using my hands.

However, I'd like to be able to tell Siri to set a certain input. Such as "Hey Siri TV to Apple TV" (which for me would be HDMI 3). As I understand it, the way to do that is by creating a button for that input. Simple enough.

However, when I do that, the button sits next to the power button and pushes the input menu down, and it's just a mess of an arrangement. And of course the more buttons I add the messier it will get. If those buttons all sat "hidden" beneath the input toggle menu, this wouldn't be an issue.

Is there an elegant solution here? Thanks!

**Comment by grzegorz914** [comment]
You can go to Home app, press long TV Tile, go to setting and press show as separate Tile. Next you can group every create button with other one in same way. Or just leave separate on Home screen.

**Comment by jscribbles** [comment]
Just wanted to make sure I responded. I am trying this solution. It's not PERFECT, but if it works, it should be clean enough. Thus far I haven't gotten it functioning quite right, but I'm going to try it a couple of more ways and then I'll respond again.

Thank you for your help!

**Comment by grzegorz914** [comment]
As we know Home app allow group only one type of services, to make this more simple You can also change type of buttons in Advanced Section in plugin config, possible is Switch, Buttons - (selectable in Home app as Outlet, Fan or Light).

**Comment by jscribbles** [comment]
It's not perfect, but I think I've got things set up how I need to get it all functioning now. Should be nice. Thanks again for the help!

**Comment by grzegorz914** [comment]
Thats all is Apple limitations, we can not make what we want to arrange tiles in Home app.
