### ISSUE TITLE
Button RC commands list

### ISSUE THREAD

**Issue by Lenn0rt** [grzegorz914/homebridge-lgwebos-tv#122]
Hi there,

Got the app completely working including all my inputs, what i cant find and would like is a physical button/switch that i can set as a scene to pause/play an app. Normally i use the middle button for this on my remote.

Could this be done/shared?

Thanks again for this great app!

**Comment by grzegorz914** [comment]
You can create this in button section:
![Zrzut ekranu 2022-01-28 o 10 52 25](https://user-images.githubusercontent.com/28867813/151525637-9b9c3c9c-005a-4b05-a8ea-8067556e8999.png)

**Comment by Lenn0rt** [comment]
Yes, thank you I've found the option in the gui but I am specifically looking for a list of rc commands that I can choose from to see what fits my needs best
