### ISSUE TITLE
Possible to use this in combination with broadlink IR?

### ISSUE THREAD

**Issue by aferrar** [grzegorz914/homebridge-lgwebos-tv#128]
Greetings,

Thanks for providing this awesome plugin. I have a broadlink IR blaster that I've been using to toggle inputs for an HDMI switch that I run for three separate screens so my inputs can be cast to whichever screen I desire at the time. Just upgraded TVs to the LG C1 and am wondering if it would be possible to have the inputs from the LG integration interact with the broadlink device? Would rather not have two separate TV elements in my homekit to juggle between for this function.

I'm guessing it's not possible, but figured I could ask. Thanks and feel free to close.

Much appreciated!

**Comment by grzegorz914** [comment]
Can not integrate other brand in this plugin.
