### ISSUE TITLE
App not available in Home App list

### ISSUE THREAD

**Issue by Stetocasa** [grzegorz914/homebridge-lgwebos-tv#132]
Hello, In the past this plugin shows my favorite app in the tile list where today just appear "Live TV":
<img width="519" alt="Screenshot 2022-07-04 alle 16 36 18" src="https://user-images.githubusercontent.com/70729310/177176028-5f1c87b2-1f5a-4900-91b8-de9f456cf52c.png">

<img width="510" alt="Screenshot 2022-07-04 alle 16 36 53" src="https://user-images.githubusercontent.com/70729310/177176097-0e6c657e-990c-48fa-9292-bcc7573e341a.png">
Available only the HDMI input

I tried to add the APP but appeared as "accessory tile" and not in the list

below my config json:

        {
            "devices": [
                {
                    "name": "LG TV",
                    "host": "19xxxxxxxx87",
                    "mac": "a0:xxxxxxxxxx65",
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "enableDebugMode": false,
                    "turnScreenOnOff": false,
                    "volumeControl": 0,
                    "infoButtonCommand": "HOME",
                    "getInputsFromDevice": false,
                    "filterSystemApps": true,
                    "enableMqtt": false,
                    "mqttAuth": false,
                    "mqttDebug": false,
                    "pictureModeControl": false,
                    "brightnessControl": false,
                    "backlightControl": false,
                    "contrastControl": false,
                    "colorControl": false
                }
            ],
            "platform": "LgWebOsTv"

**Comment by Stetocasa** [comment]
the app are corrected reported in LG app
![IMG_4905](https://user-images.githubusercontent.com/70729310/177176565-52b84138-ed37-4c9a-a106-37a9d61edecb.PNG)

**Comment by grzegorz914** [comment]
You have disabled getInputsFromDevice, set this to true and restart The plugin.

**Comment by Stetocasa** [comment]
> You have disabled getInputsFromDevice, set this to true and restart The plugin.

I already tried but generated 65 different tiles as accessory

**Comment by grzegorz914** [comment]
Close and open home app again and all will be OK
