### ISSUE TITLE
Child bridge duplicate

### ISSUE THREAD

**Issue by schweppy** [grzegorz914/homebridge-lgwebos-tv#135]
Hello
I have been using this plugin for ages with no issue but slowly migrating all plugins to child bridges.
Today I moved webostv to a child bridge, deleted the TV from home app, deleted the cached accessory in home bridge UI X and then tried to add the new child bridge device in the home app.

However, when I click on add new device in home app, the old TV device is still showing as an accessory to add and it fails when I try to add the new device. Any ideas?

Cheers

**Comment by grzegorz914** [comment]
Anything in the log console?

**Comment by schweppy** [comment]
Ive got one of the devices to add now after several restarts. Log is normal, no faults. Not sure why the other device remains. I tried to add it but it says setup code incorrect even though my child bridges are all set to the same code as the main bridge.

**Comment by grzegorz914** [comment]
May be try restart your iPhone/iPad

**Comment by schweppy** [comment]
I did do that but I've just restarted a few more times and its disappeared! Thank you!!
