### ISSUE TITLE
Error in Homebridge : no response in HK

### ISSUE THREAD

**Issue by ppernet** [grzegorz914/homebridge-lgwebos-tv#138]
Hi,

Thank you for your work on this plugin.

Since few days, Homebridge show this error and if I try to switch on TV, no response appears in HK.

`[homebridge-lgwebos-tv] This plugin threw an error from the characteristic 'Active': Unhandled error thrown inside write handler for characteristic: stae is not defined. See https://homebridge.io/w/JtMGR for more info.`

Any idea about this error and how to resolve it ?

Thanks

**Comment by grzegorz914** [comment]
Ups.. will be fixed today, thanks for report.

**Comment by SUPERSAWBO** [comment]
I had this issue also. Updated and now the plug-in won’t turn on the TV. All other actions work but not the turn on.

**Comment by grzegorz914** [comment]
Already fixed in 2.2.2
