### ISSUE TITLE
I can't add LG TV to Homekit.

### ISSUE THREAD

**Issue by RemoteMaple9** [grzegorz914/homebridge-lgwebos-tv#14]
Hello,
I had my LG TV in Homekit for a long time. One day it stopped working and the TV was unreachable, then I deleted it from Homekit. The TV is still connected to homebridge and is working, but i can't add it to my Homekit. I tried restart it...
What should I do with that?

**Comment by grzegorz914** [comment]
Change its name, restart homebridge and try add again.

**Comment by Spanishu** [comment]
I have set it up new. I can manage it from homebridge but it does not appear on HomeKit

**Comment by grzegorz914** [comment]
See my previous post.

**Comment by grzegorz914** [comment]
I close this, not related as issue for plugin.
