### ISSUE TITLE
Error During Installation

### ISSUE THREAD

**Issue by iceage2609** [grzegorz914/homebridge-lgwebos-tv#140]
I am using Homebridge on Synology Nas, when i try to install the plugin every time i ge t this error message, any idea what seems to be the problem ? I am not an expert , so i try to find out what causing this.

Thanks in advance 
![Screenshot 2022-09-28 at 15 48 10](https://user-images.githubusercontent.com/102951608/192783072-041da7b3-99e0-4c99-8936-b2f4ca476a13.png)

**Comment by grzegorz914** [comment]
Here is no any problem with my plugin, check your NPM and Node installation.
