### ISSUE TITLE
RC App extra buttons

### ISSUE THREAD

**Issue by uziel200** [grzegorz914/homebridge-lgwebos-tv#143]
When I recent open RC app from control center it appear some extra buttons at the top. I wonder if is possible to enable?

![image](https://user-images.githubusercontent.com/5307189/206092824-6c6311bd-d430-4fb6-bf27-c8ae72d1a8a6.jpeg)

Or maybe it possible to enable all button like an Apple TV 

![image](https://user-images.githubusercontent.com/5307189/206092988-d297228b-954e-494c-92f4-826ae241afa9.jpeg)

Is one of this options possible?

**Comment by grzegorz914** [comment]
Not possible at this time.
