### ISSUE TITLE
Added device to config and accepted pairing but not showing up in Home app

### ISSUE THREAD

**Issue by KE55ARD** [grzegorz914/homebridge-lgwebos-tv#144]
I've added the bridge to my Apple Home and setup the device in the config and even got as far as accepting the pairing prompt on the TV and the log in HomeBridge now says it's connecting whenever I start the bridge, but I do not see a device in the Home app at all.

My TV model is OLED55B16LA in case that helps at all.

**Comment by grzegorz914** [comment]
are you added the accessory itself nit the bridge to the home.app https://github.com/grzegorz914/homebridge-lgwebos-tv/wiki#adding-to-homekit

**Comment by grzegorz914** [comment]
If resolved I close this.

**Comment by eleventhaus** [comment]
I'm having this issue however I did follow the instructions and was able to add the TV.

I removed the TV from Homekit but when I tried to readd it following the instructions it does not show up when I click _More Options_. I have tried uninstalling the plugin and reinstalling. Can't seem to get the TV to show back up under the _More Options_.

**Comment by grzegorz914** [comment]
@eleventhaus 
are you try this https://github.com/grzegorz914/homebridge-lgwebos-tv/wiki#troubleshooting
