### ISSUE TITLE
TV status

### ISSUE THREAD

**Issue by alloploid** [grzegorz914/homebridge-lgwebos-tv#145]
Hi,

Is it possible to read some status from TV to HomeKit? e.g. if the screen saver is on?

**Comment by grzegorz914** [comment]
It is possible but not implemented yet, What do You want to do with this info?

**Comment by alloploid** [comment]
I want to make some automation that can run e.g. HBO Max, select user and display some specific screen in the app. But if screen saver is enabled, the first click won't work. Maybe you have some idea of how to control apps?

**Comment by grzegorz914** [comment]
added https://github.com/grzegorz914/homebridge-lgwebos-tv/releases/tag/v2.3.0

**Comment by alloploid** [comment]
Hi, It was fast. Thank you very much!

Do you see any way to read some status/data from the application? e.g. if the select account screen is on?

**Comment by grzegorz914** [comment]
No, this info is not available .
