### ISSUE TITLE
Button issue in HomeKit

### ISSUE THREAD

**Issue by alloploid** [grzegorz914/homebridge-lgwebos-tv#146]
Hi,

I'm facing an issue with the control button in HomeKit. If I click any button (screen mode, menu, arrow, okay etc), it stays enabled. I need to click in a second time to unclick it. Only the click from unclick -> enabled trigger actions.

![IMG_C99983668C7C-1](https://user-images.githubusercontent.com/91637681/208287591-f56321d6-95da-42a3-9373-dcb4fe18f346.jpeg)

**Comment by grzegorz914** [comment]
please try 2.3.0-beta.0 and let me know

**Comment by alloploid** [comment]
It work perefect now. Thank You!
