### ISSUE TITLE
Volume Slider and Information Button

### ISSUE THREAD

**Issue by Spondes90** [grzegorz914/homebridge-lgwebos-tv#147]
Hi,

Thank you for creating this plugin. I am new to Homebridge / HOOBS. I have configured the plugin, however, I have come across a couple of issues I hope you can help with.

1. The volume slider acts as a mute button and does not adjust the volume of my Sonos Beam. For example, 0% = mute and 1-100% = volume last set using hardware controller. However, if I use the Apple RC the volume buttons on my iPhone work correctly by adjusting the Sonos Beam up/down. Is there a way to use the slider in Home app the same way so that voice control with Siri can be used to turn the TV volume up/down?

2. The "i" button in the Apple RC acts as the Info button regardless of setting _switchInfoMenu_ to true or false. How can the "i" button be used as the Home button?

Many thanks for your help.

homebridge-lgwebos-tv v2.3.1
iPhone 13 Pro iOS 16.2

**Comment by grzegorz914** [comment]
Adjust volume of external speakers using slider is not implemented yet.
The function of “i
![2ACF9590-B1D9-4E9A-ACD6-23C2DB1CD174](https://user-images.githubusercontent.com/28867813/209065683-3f9ade45-43fc-4b97-a1fb-a391be453150.jpeg)
” button is selectable in plugin Config.
