### ISSUE TITLE
TV and Sensors not showing in Home App

### ISSUE THREAD

**Issue by SamerBerjawi** [grzegorz914/homebridge-lgwebos-tv#150]
Hi,

I have just installed homebridge and your plugin, and connected the plugin to HomeKit as a child Bridge. I can see the bridge in the Home App but it doesn’t have any devices. 
In homebridge, I can see the accessories and the motion sensors.

i tried deleting the persist and accessories but that didn’t work. 

Any idea?

thanks,
Samer

**Comment by grzegorz914** [comment]
The AccessoryInfo need to be added to Hom.app se: https://github.com/grzegorz914/homebridge-lgwebos-tv/wiki#adding-to-homekit

**Comment by SamerBerjawi** [comment]
Perfect! Works like a charm. Thanks a lot
