### ISSUE TITLE
WebOs 3.30.14 - not working 

### ISSUE THREAD

**Issue by fadelguy** [grzegorz914/homebridge-lgwebos-tv#151]
Hi,

I have been using this plugin for a few months.
Today the TV was updated to version 3.30.14 and the plugin stopped working.  I'm the logs I see that plugin can't connect to the TV.

09/01/2023, 19:09:01HomeLgWebOsTvDevice: x.x.x.x LG TV, debug: Socked connect error: Error: read ECONNRESET, reconnect in 5s.

Please advise.

**Comment by grzegorz914** [comment]
Debug log please.

**Comment by grzegorz914** [comment]
Check Your tv config, may be resets networks settings during update, Check also MAC address.

**Comment by fadelguy** [comment]
I check the tv network and it's the same as plugin configuration.

All works fine until the tv update 3.30.14.

**Comment by grzegorz914** [comment]
Log connect app is enabled too?

**Comment by grzegorz914** [comment]
Looks like fw. 3.30.14. break connection to tv, here in homebassistant same problem https://github.com/home-assistant/home-assistant.io/pull/25669.

**Comment by thecode** [comment]
> Looks like fw. 3.30.14. break connection to tv, here in home assistant same problem [home-assistant/home-assistant.io#25669](https://github.com/home-assistant/home-assistant.io/pull/25669).

See https://github.com/home-assistant-libs/aiowebostv/pull/112 for how we fixed new firmware problems for Home Assistant

**Comment by grzegorz914** [comment]
@fadelguy 
try 2.3.8-beta.0 and let me know

**Comment by fadelguy** [comment]
I don't see it on hoobs.
The last beta version I see is 2.3.7-beta.15

**Comment by grzegorz914** [comment]
try install manually from console
sudo npm install -g homebridge-lgwebos-tv@2.3.8@beta.1

**Comment by fadelguy** [comment]
![image](https://user-images.githubusercontent.com/32434449/212136677-9bf8f47c-64ef-4975-b301-3f44562f50cf.jpeg)

Can't install

**Comment by grzegorz914** [comment]
Use this method
https://github.com/hoobs-org/HOOBS/issues/186#issuecomment-538745028

**Comment by grzegorz914** [comment]
I will push as release, wait a few minutes

**Comment by grzegorz914** [comment]
2.3.8 published

**Comment by fadelguy** [comment]
Just update to version 2.3.8
The plugin still not working 


12/01/2023, 20:12:52HomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socked connect error: Error: connect EHOSTUNREACH 192.168.50.54:3000, reconnect in 5s.
12/01/2023, 20:13:00HomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socked connect error: Error: connect EHOSTUNREACH 192.168.50.54:3000, reconnect in 5s.
12/01/2023, 20:13:08HomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socked connect error: Error: connect EHOSTUNREACH 192.168.50.54:3000, reconnect in 5s.

**Comment by grzegorz914** [comment]
I don’t thing so,  the log is from previous version.

**Comment by grzegorz914** [comment]
Ups, wait next version

**Comment by grzegorz914** [comment]
Try 2.3.9 and enable SSL WebSocket in plugin settings

**Comment by fadelguy** [comment]
Updated to 2.3.9
But don't see this option on plugin configuration

**Comment by grzegorz914** [comment]
![Uploading DA7F2541-E779-4FED-B01D-04D0A8034B9B.jpeg…]()

**Comment by grzegorz914** [comment]
![92601580-811D-4C14-B59C-523078D26267](https://user-images.githubusercontent.com/28867813/212174280-1664fb02-614f-40d4-9702-1a1dc3690aee.jpeg)

**Comment by fadelguy** [comment]
Don't see this option

![image](https://user-images.githubusercontent.com/32434449/212174734-511b929a-7575-461f-b3aa-b8b05277a685.jpeg)

**Comment by grzegorz914** [comment]
The key is sslWebSocket

**Comment by fadelguy** [comment]
New log error:

12/01/2023, 22:46:52HomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socked connect error: Error: unable to get local issuer certificate, reconnect in 5s.

**Comment by grzegorz914** [comment]
try 2.3.10

**Comment by fadelguy** [comment]
Updated to 2.3.12

Still not working 

13/01/2023, 09:00:11HomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socked connect error: Error: connect EHOSTUNREACH 192.168.50.54:3001, reconnect in 5s.
13/01/2023, 09:00:18HomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socked connect error: Error: unable to get local issuer certificate, reconnect in 5s.

**Comment by grzegorz914** [comment]
Try 2.3.13

**Comment by fadelguy** [comment]
Still not working 

13/01/2023, 12:47:34HomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socked connect failed: Error: connect EHOSTUNREACH 192.168.50.54:3001, reconnect.
13/01/2023, 12:47:37HomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socked connect failed: Error: connect EHOSTUNREACH 192.168.50.54:3001, reconnect.
13/01/2023, 12:47:40HomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socked connect failed: Error: connect EHOSTUNREACH 192.168.50.54:3001, reconnect.

**Comment by grzegorz914** [comment]
2.4.0 beta is available to test.

**Comment by grzegorz914** [comment]
2.4.0 released

**Comment by fadelguy** [comment]
Just update to the last version 2.4.2.

Can't start the bridge.
Only after I removed this plugin configuration from json config the bridge start again.

**Comment by grzegorz914** [comment]
Can you post your config.json, debug log, and install environment? Here all working correct.

**Comment by fadelguy** [comment]
I removed the sslWebSocket key and now the bridge start.
But still the plugin not working with the tv:

1/14/2023, 6:53:25 PMHomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socket send heart beat.
1/14/2023, 6:53:25 PMHomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socked closed.
1/14/2023, 6:53:30 PMHomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socket send heart beat.
1/14/2023, 6:53:30 PMHomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socked closed.
1/14/2023, 6:53:35 PMHomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socket send heart beat.
1/14/2023, 6:53:35 PMHomeLgWebOsTvDevice: 192.168.50.54 LG TV, debug: Socked closed.

**Comment by grzegorz914** [comment]
you need enable ssl for your firmware, can you post complete debug log after plugin restart?

**Comment by fadelguy** [comment]
Just update to 2.4.3
Still not working
When sslWebSocket enabled, the bridge not start and there no logs for this plugin.
This is my config:

        {
            "platform": "LgWebOsTv",
            "devices": [
                {
                    "name": "LG TV",
                    "host": "-",
                    "mac": "-",
                    "turnScreenOnOff": false,
                    "volumeControl": 1,
                    "switchInfoMenu": true,
                    "getInputsFromDevice": false,
                    "inputs": [
                        {
                            "name": "Partner tv",
                            "reference": "co.il.partnertv",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "Netflix",
                            "reference": "netflix",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "GeForce NOW",
                            "reference": "com.geforcenow.play",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "YouTube",
                            "reference": "youtube.leanback.v4",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "Apps",
                            "reference": "com.webos.app.discovery",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "חפש",
                            "reference": "com.webos.app.voice",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "voiceweb",
                            "reference": "com.webos.app.voiceweb",
                            "type": "APPLICATION",
                            "mode": 0
                        }
                    ],
                    "disableLogInfo": true,
                    "enableDebugMode": true,
                    "sslWebSocket": true
                }
            ]
        }

**Comment by grzegorz914** [comment]
try 2.4.4 but I don't have no idea why not start the bridge in your installation, may be hoobs specific issue

**Comment by fadelguy** [comment]
In the previous versions I did not experience this problem that the bridge not start.

Why I don't see the ssl config on hoobs ui?

**Comment by grzegorz914** [comment]
Here all start correct with ssl and without ssl

![Zrzut ekranu 2023-01-14 o 18 32 11](https://user-images.githubusercontent.com/28867813/212487109-9b136cd9-240e-4669-81e2-1b445a069cd4.png)

**Comment by grzegorz914** [comment]
If the bridge docent start must be something wrong with your installation

**Comment by grzegorz914** [comment]
I don't know why you not see all options in HOOBS, you need report this problem on HOOBS support. Best practice is to use Homebridge with Config UI X native.

**Comment by fadelguy** [comment]
Updated to 2.4.4-beta.3

Now it's working!!!!

Thank you very much!

**Comment by grzegorz914** [comment]
2.4.4 is released now,
