### ISSUE TITLE
Plugging /Bridges added but LG WEBOS-TV missing within home app 

### ISSUE THREAD

**Issue by ffidel** [grzegorz914/homebridge-lgwebos-tv#152]
Not sure if this is related to the 16.2 HomeKit issue, I had to remove everything and re add the home now the I see the accessory within the home. restarted child bridge and all still no luck. anyone noticing something similar

**Comment by grzegorz914** [comment]
You need add the Accessory itself not the bridge.

**Comment by ffidel** [comment]
So I have scan the QR after setting up the bridges under + add Accessories like I would normally do, go through  the whole process etc once completed is where I don't have anything. and its not even showing under accessories in the homebride accessories portal 


also tried the steps below " 
If for some reason the device is not displayed in HomeKit app try this procedure:
Go to ./homebridge/persist macOS or /var/lib/homebridge/persist for RPI.
Remove AccessoryInfo.xxx file which contain Your device data: {"displayName":"LG TV"}
Next remove IdentifierCashe.xxx file with same name as AccessoryInfo.xxx
Restart Homebridge and try add it to the HomeKit app again.

**Comment by ffidel** [comment]
After un installing the plugin I restarted home bridge clear out the Cache accessories I was able to get this one to come up on the next install and set up
