### ISSUE TITLE
Automation based on selected input

### ISSUE THREAD

**Issue by DataFran** [grzegorz914/homebridge-lgwebos-tv#156]
Hello!
I'm trying to create an automation to trigger when I select a specific input (in this case HDMI1). I can't figure out how to do that with the plugin as it exists today. Is this possible, and am I missing something, or could options to allow this be added in the future?
Thanks!

**Comment by grzegorz914** [comment]
Right now the motion sensor trigger every channels change, not if switch to specific input as you want. It can be added this possibility in future.

**Comment by DataFran** [comment]
I upgraded to this version, but I can't figure out how to implement this. What am I missing?

**Comment by grzegorz914** [comment]
Sensor—-Inputs section in plugin settings

**Comment by DataFran** [comment]
Hmm, I've tried adding everything I can think of to get this working, this is my config. What am I doing wrong?

           "devices": [
                {
                    "name": "LG TV Main",
                    "host": removed for pasting,
                    "mac": removed for pasting,
                    "getInputsFromDevice": true,
                    "filterSystemApps": true,
                    "sensorPower": false,
                    "sensorVolume": false,
                    "sensorMute": false,
                    "sensorInput": true,
                    "sensorChannel": false,
                    "sensorScreenOnOff": false,
                    "sensorScreenSaver": false,
                    "sensorInputs": [
                        {
                            "name": "HDMI 1",
                            "reference": "com.webos.app.hdmi1",
                            "displayType": 0
                        }
                    ],
                    "brightnessControl": false,
                    "backlightControl": false,
                    "contrastControl": false,
                    "colorControl": false,
                    "pictureModeControl": false,
                    "enableDebugMode": false,
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "turnScreenOnOff": false,
                    "sslWebSocket": false,
                    "enableMqtt": false,
                    "mqttAuth": false,
                    "mqttDebug": false
                }
            ],
            "platform": "LgWebOsTv"

**Comment by grzegorz914** [comment]
All is Ok here, what is your problem?

**Comment by DataFran** [comment]
When I add the accessory to Homekit, there is no sensor associated with the TV for the specific input change. I can automate using *any* input change, but not specifically when selecting HDMI 1.

**Comment by grzegorz914** [comment]
The sensors are here:
![688A3EA9-427F-4B2D-B07D-63531CBE7E80](https://user-images.githubusercontent.com/28867813/214644360-864ffaa3-1260-4724-8c3a-9bf085ae073a.jpeg)
![B5B8B726-03D0-4EAB-8178-0E2E73DE8B2C](https://user-images.githubusercontent.com/28867813/214644374-6926a811-5ad2-4cae-9127-a81d00d0dbf8.jpeg)

**Comment by DataFran** [comment]
Huh, when I enable the SensorInput:true, I get the general motion sensor (detects motion at any input change), but when I create a SensorInput it doesn't appear in HomeKit. Very strange. Only the general motion detector appears.

 ],
                    "sensorPower": false,
                    "sensorVolume": false,
                    "sensorMute": false,
                    "sensorInput": true,
                    "sensorChannel": false,
                    "sensorScreenOnOff": false,
                    "sensorScreenSaver": false,
                    "sensorInputs": [
                        {
                            "name": "XBox",
                            "reference": "com.webos.app.hdmi1",
                            "displayType": 0
                        },
                        {
                            "name": "HDMI 4",
                            "reference": "com.webos.app.hdmi4",
                            "displayType": 0
                        }
                    ],

**Comment by grzegorz914** [comment]
sensrInput report on every channel change, sensorInputs report on change to created sensor, this are 2 different sensors. As you see on my screenshots it’s appear in Home app correct. If you load inputs from device always enable filter system app because HomeKit have limitation of created services and sensors can be omitted.

**Comment by grzegorz914** [comment]
try 2.5.10, in this version reduced max inputs to 80, this leave some services for sensors, etc..
