### ISSUE TITLE
The state in Homekit displays ON despite the TV is off.

### ISSUE THREAD

**Issue by vahov** [grzegorz914/homebridge-lgwebos-tv#16]
When operated with original remote and turning the TV off, the state in Homekit remains ON. Below you can see, that I shut the TV down 08:59 but STANDBY state in Homebridge, which changes the state in Homekit, appeared 09:03 when I refreshed Home app. I have wall mounted iPads and it would be nice when the OFF state will change without refreshing. The ON command works, when I turn the TV on with original remote the state changes immediately in Homekit. 
Edit: for what it is worth the input state changes immediately in Homekit, the problem is only with off command.

[5/2/2020, 08:59:42] [LgWebOsTv] Device: 192.168.1.88, get current Power state successful: ON
[5/2/2020, 08:59:42] [LgWebOsTv] Device: 192.168.1.88, get current Input successful: 
[5/2/2020, 08:59:49] [LgWebOsTv] Device: 192.168.1.88, name: II Elutuba TV, state: Offline
[5/2/2020, 08:59:49] [LgWebOsTv] Device: 192.168.1.88, disconnected.
[5/2/2020, 09:03:36] [LgWebOsTv] Device: 192.168.1.88, get current Power state successfull, state: STANDBY

**Comment by PrzemyslawKlys** [comment]
If you have OLED TV according to developer of the other plugin it is because OLED TVs try to "save" screen when they shutdown. During that state it's not possible to get a proper state of TV.

**Comment by vahov** [comment]
Yes but this is not OLED. I tried the other plugin, homebridge-webos-tv, and it it works correctly so there is something wrong with this plugin. There is a closed issue too where it is stated that you can get the correct state to Homekit only by manually refreshing. This is not expected behaviour though.

**Comment by grzegorz914** [comment]
Update to latest ver. and get feedback.

**Comment by vahov** [comment]
It is working now, thank you.

**Comment by ramirocaballero** [comment]
Hello!! I have the same issue, but don't understand what to do.
