### ISSUE TITLE
Power On doesn’t work after a few hours off. 

### ISSUE THREAD

**Issue by mattyd22201** [grzegorz914/homebridge-lgwebos-tv#160]
I’ve had this issue for a while, and it could be a setting on my TV but I’ve tired everything. I have an LG OLED77GXPUA and while it has built in HomeKit, it’s limited in what it does. Hoping someone can help. When I power the TV off and on, it works fine. However if I power that TV off at night, it’s like after a certain amount of hours prevents the TV from turning back on using HomeKit. I’ve tried using the option to just turn the screen off which works, but after a couple days I need to manually power it off to do a refresh for it or a message pops up every time. I could use both the embedded HomeKit and the plug in to accomplish this but then I’ll have two TVs and 2 remotes.

**Comment by grzegorz914** [comment]
Are you enabled wake on lan wlan in tv settings?

**Comment by mattyd22201** [comment]
I can't find a Wake On Lan setting anywhere in my settings but I saw something about disabling Quick Start+ so I did that and still had the issue this morning. It worked okay after about 3.5 hours, but it was about 7 hours over night and it didnt turn back on.

**Comment by mattyd22201** [comment]
That is on, but I dont have it connect to WiFi, I have it connected via ethernet. Do I need to have it on Wifi?

**Comment by grzegorz914** [comment]
Just try it.

**Comment by mattyd22201** [comment]
Will do. Ill report back tomorrow AM. Thank you!

**Comment by mattyd22201** [comment]
It didn’t work the first night, but noticed the Wi-Fi connection went offline so I unplugged the connection Ethernet and that seemed to do the trick. It’s worked the past 2 days without issue. Thanks for your help!
