### ISSUE TITLE
Buttons not available

### ISSUE THREAD

**Issue by R-Rennert** [grzegorz914/homebridge-lgwebos-tv#161]
Hi,

since Version 2.6.3 buttons no longer available in HomeKit.  Back to V2.6.1 and ist works. Have set as Remote Control.

**Comment by grzegorz914** [comment]
check your config buttons display type

**Comment by grzegorz914** [comment]
ups, will be fixed soon

**Comment by R-Rennert** [comment]
Hi,Thx for V2.6.6, but only available first button, other not available. First set as button, but displayed as switch.Thx for your workAm 10.02.2023 um 16:59 schrieb Grzegorz ***@***.***>:﻿
Closed #161 as completed via 99b1b54.

**Comment by grzegorz914** [comment]
It is always as switch only different display in HomeKit app, name corrected in 2.6.7

**Comment by R-Rennert** [comment]
Hi,Not working.I send you some pictures. In 2.6.1 i have displayed 3 buttons for Play, Pause and Menu OK. up to 2.6.2 only first.Am 10.02.2023 um 18:04 schrieb Grzegorz ***@***.***>:﻿
It is always as switch only different display in HomeKit app, name corrected in 2.6.7

**Comment by grzegorz914** [comment]
All buttons working fine 2.6.7 
![Uploading FF72E173-7274-4106-95A4-171037B2064A.jpeg…]()

**Comment by R-Rennert** [comment]
No only in 2.6.1 and early versions. I have set 3 buttons for remote control and display as button in HK, but only displayed the first i setIn Settings.Am 10.02.2023 um 19:05 schrieb Grzegorz ***@***.***>:﻿
All buttons working fine 2.6.7

**Comment by grzegorz914** [comment]
post your config please

**Comment by R-Rennert** [comment]
"devices": [                {                    "name": "LG TV",                    "host": "192.168.178.26",                    "mac": "04:4E:AF:79:E9:30",                    "getInputsFromDevice": true,                    "filterSystemApps": false,                    "buttons": [                        {                            "name": "TV Pause",                            "mode": 2,                            "command": "PAUSE",                            "displayType": 0                        },                        {                            "name": "TV Play",                            "mode": 2,                            "command": "PLAY",                            "displayType": 0                        },                        {                            "name": "TV OK",                            "mode": 2,                            "command": "ENTER",                            "displayType": 0                        }                    ],                    "sensorPower": false,                    "sensorVolume": false,                    "sensorMute": false,                    "sensorInput": false,                    "sensorChannel": false,                    "sensorScreenOnOff": false,                    "sensorScreenSaver": false,                    "brightnessControl": false,                    "backlightControl": false,                    "contrastControl": false,                    "colorControl": false,                    "pictureModeControl": false,                    "enableDebugMode": false,                    "disableLogInfo": false,                    "disableLogDeviceInfo": false,                    "turnScreenOnOff": false,                    "sslWebSocket": false,                    "enableMqtt": false,                    "mqttAuth": false,                    "mqttDebug": false                }            ],            "_bridge": {                "username": "0E:9A:25:48:21:29",                "port": 53312            },            "platform": "LgWebOsTv"        },Am 10.02.2023 um 19:42 schrieb Grzegorz ***@***.***>:﻿
post your config please

**Comment by grzegorz914** [comment]
please enable filter system app if you get inputs from device

**Comment by R-Rennert** [comment]
Hi,Have enabled hide system apps and it works. Thanks for your help. I understand why it works on 2.6.1 and early without this setting.Am 10.02.2023 um 20:00 schrieb Grzegorz ***@***.***>:﻿
please enable filter system app if you get inputs from device
