### ISSUE TITLE
saving settings problem

### ISSUE THREAD

**Issue by Gutrum1986** [grzegorz914/homebridge-lgwebos-tv#163]
The plugin not saving changes insettings at all!
im added some inputs and buttons but after restart the changes gone

**Comment by grzegorz914** [comment]
I don't see the issue, all is saved correct on my side. Check write permission, etc...

**Comment by grzegorz914** [comment]
What a browser you use?

**Comment by Gutrum1986** [comment]
Chrome

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by grzegorz914** [comment]
Please try to use safari
