### ISSUE TITLE
Unexpected end of JSON input while parsing near '...KDT/tQ9FtqCY/b/zKKL+s'

### ISSUE THREAD

**Issue by Klariff** [grzegorz914/homebridge-lgwebos-tv#17]
When installing the package I get the following

`Unexpected end of JSON input while parsing near '...KDT/tQ9FtqCY/b/zKKL+s'`

**Comment by grzegorz914** [comment]
Complete log please

**Comment by Klariff** [comment]
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> websocket@1.0.31 install /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

sh: 1: cannot create builderror.log: Permission denied
+ homebridge-lgwebos-tv@0.7.19
added 126 packages from 106 contributors in 28.748s

**Comment by grzegorz914** [comment]
Nothing wrong from the package.
https://medium.com/@codewin/npm-warn-deprecated-request-2-88-2-b6da20766fd7

**Comment by Klariff** [comment]
Don't focus on that, the log shows a permission denied

**Comment by grzegorz914** [comment]
Permission denied have nothing to do with this plugin, is something wrong with Your installations and directory permission.
