### ISSUE TITLE
Change ping/update interval

### ISSUE THREAD

**Issue by epheterson** [grzegorz914/homebridge-lgwebos-tv#172]
I’m not seeing what the refresh rate of pinging the TV for updates is or how to change it. 

I want an automation to run by turning the tv on but it’s pretty slow. I’d like to check the rate and maybe change it to 5s or so, maybe less? Not sure what the cost/overhead is.

**Comment by grzegorz914** [comment]
its not a pin or poll, here is web socket, if the tv connect to then the data is present.

**Comment by epheterson** [comment]
Is there any way to make the TV form it faster when turning on? I see in Homebridge logs it takes a while.

**Comment by grzegorz914** [comment]
try latest beta.3

**Comment by epheterson** [comment]
It does seem a bit faster! What’s changed?

**Comment by Glujaz** [comment]
I have the same issue as well, but in the other way : when turning it off.

I have an automation, and it takes like 10min to detect it's been turned off.
So maybe, again, i suppose this also needs an update interval.

(Turning it manually off works, but HomeKit sees it on again after a second)

i use a video projector with webos 3 I think

**Comment by grzegorz914** [comment]
This issue should be solved with 2.14.x
