### ISSUE TITLE
How I can get remote like from your picture?

### ISSUE THREAD

**Issue by zalewski-b** [grzegorz914/homebridge-lgwebos-tv#182]
![inputs](https://github.com/grzegorz914/homebridge-lgwebos-tv/assets/61246068/fbd97b67-968c-4752-8731-a1ca9d93238a)

My config file: 

           "devices": [
                {
                    "name": "LG CX",
                    "host": "192.*****.129",
                    "mac": "B****5",
                    "getInputsFromDevice": false,
                    "filterSystemApps": false,
                    "disableLoadDefaultInputs": false,
                    "inputs": [
                        {
                            "name": "HDMI 3",
                            "reference": "com.webos.app.hdmi3",
                            "mode": 0
                        },
                        {
                            "name": "HDMI 4",
                            "reference": "com.webos.app.hdmi4",
                            "mode": 0
                        },
                        {
                            "name": "Netflix",
                            "reference": "netflix",
                            "mode": 0
                        },
                        {
                            "name": "BBC ONE HD",
                            "reference": "1_45_101_101_16521_17540_9018",
                            "mode": 1
                        }
                    ],
                    "buttons": [
                        {
                            "name": "HDMI 3",
                            "reference": "com.webos.app.hdmi3",
                            "mode": 0,
                            "displayType": 0
                        },
                        {
                            "name": "BBC ONE HD",
                            "reference": "1_45_101_101_16521_17540_9018",
                            "mode": 1,
                            "displayType": 0
                        },
                        {
                            "name": "Menu Up",
                            "mode": 2,
                            "command": "UP",
                            "displayType": 0
                        }
                    ],
                    "backlightControl": false,
                    "brightnessControl": false,
                    "contrastControl": false,
                    "colorControl": false,
                    "pictureModeControl": false,
                    "pictureModes": [
                        {
                            "name": "Cinema",
                            "reference": "cinema"
                        }
                    ],
                    "volumeControl": 0,
                    "soundModeControl": false,
                    "soundModes": [
                        {
                            "name": "Cinema",
                            "reference": "movie"
                        }
                    ],
                    "sensorPower": false,
                    "sensorPixelRefresh": false,
                    "sensorVolume": false,
                    "sensorMute": false,
                    "sensorInput": false,
                    "sensorChannel": false,
                    "sensorSoundMode": false,
                    "sensorPictureMode": false,
                    "sensorScreenOnOff": false,
                    "sensorScreenSaver": false,
                    "sensorInputs": [
                        {
                            "name": "HDMI 1",
                            "reference": "com.webos.app.hdmi1",
                            "displayType": -1
                        }
                    ],
                    "enableDebugMode": false,
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "disableTvService": false,
                    "turnScreenOnOff": false,
                    "sslWebSocket": false,
                    "infoButtonCommand": "MENU",
                    "enableRestFul": false,
                    "restFulPort": 3000,
                    "restFulDebug": false,
                    "enableMqtt": false,
                    "mqttDebug": false,
                    "mqttHost": "192.168.1.33",
                    "mqttPort": 1883,
                    "mqttClientId": "",
                    "mqttPrefix": "home/lg",
                    "mqttAuth": false,
                    "mqttUser": "user",
                    "mqttPass": "password"
                }
            ],
            "platform": "LgWebOsTv"

**Comment by grzegorz914** [comment]
This is built-in function in the iOS/ipadOS and placed in Control Center
