### ISSUE TITLE
Motion sensor on input with multiple devices

### ISSUE THREAD

**Issue by JFizDaWiz** [grzegorz914/homebridge-lgwebos-tv#186]
I essentially want to set up an automation to turn off all lights when my Blu-ray player is on. 

I see I can do this with specific inputs like HDMI2 but my HDMI2 is a receiver with multiple devices (Apple TV, Blu-ray and Nintendo Switch)

When I am watching one of these devices, the TV shows HDMI 2 and the name of the device (ex. Apple TV shows “Living Room” and Blu-ray player shows “Unknown”)

is there any way to set up a motion sensor for a specific device in this scenario?

**Comment by grzegorz914** [comment]
In this case you need homebridge plugi for your Receiver or connect devices direct to TV.
