### ISSUE TITLE
Config missing, not showing in home app

### ISSUE THREAD

**Issue by GillesWi** [grzegorz914/homebridge-lgwebos-tv#187]
Hi, when setting up I do not see the Tv in my Apple Home. The logs say this

<img width="1366" alt="image" src="https://github.com/grzegorz914/homebridge-lgwebos-tv/assets/77160203/22113379-3943-4285-a5ba-73ee2f47fb04">

**Comment by grzegorz914** [comment]
Are you set correct MAC address in config?

**Comment by GillesWi** [comment]
Thank you for your fast response! The MAC should be correct. Or should I remove the dots? 
<img width="778" alt="Screenshot 2023-12-25 at 10 43 15" src="https://github.com/grzegorz914/homebridge-lgwebos-tv/assets/77160203/4f8dfcf4-9521-464a-b62d-55f6e7a9f932">

**Comment by grzegorz914** [comment]
Yor mac format is not correct< correct is xx:xx:xx:xx:xx:xx

**Comment by GillesWi** [comment]
Works now! Thank you so much for the help:)
