### ISSUE TITLE
Correct the order of inputs (issue since iOS 17)

### ISSUE THREAD

**Issue by badgertastic** [grzegorz914/homebridge-lgwebos-tv#188]
Hi. I think since iOS 17 (some other plugins have updated to fix the behaviour) the order of inputs is per example:

5
3
1
2
4

Can it be changed back to original:

1
2
3
4
5

Thanks.

Example of issue resolved in [another plugin](https://github.com/tavicu/homebridge-samsung-tizen/issues/648)

**Comment by badgertastic** [comment]
I mean to display the inputs in the same order as configured, not just sorting them.

**Comment by grzegorz914** [comment]
Please try 2.15.0-beta and let me know,  here you can select in plugin config different sorting options `None`, `Alphabetically Name`, `Alphabetically Reference`

**Comment by grzegorz914** [comment]
Yes, denon is ready to test

**Comment by grzegorz914** [comment]
I close this as complete. 2.15.0 released

**Comment by badgertastic** [comment]
Thanks again
