### ISSUE TITLE
LG G1 and C2 not turning on after some time

### ISSUE THREAD

**Issue by miguelpruivo** [grzegorz914/homebridge-lgwebos-tv#189]
Hi, I have WoL enabled on both TVs and both can be properly controlled within a few minutes of being off as well as when they are on. The problem is when they are left off for more than 30 minutes or so and enter in a deep sleep state where I can't turn them on at all with the Home app.

My G1 is wired connected and my C2 is wifi connected, so I got to try both ways, but issues seems to happen on both approaches as well.

**Comment by grzegorz914** [comment]
Looks like the TV after some standby time disable WOL or your router disable connection to TV. Check your local environment because this behavior have nothing to do with this plugin.
