### ISSUE TITLE
Bridge appears to be paired, but not TV

### ISSUE THREAD

**Issue by siobhanellis** [grzegorz914/homebridge-lgwebos-tv#196]
Hi there,

I have configured the TV in the plugin. I can get the bridge to appear in HomeKit, and then I add it.... The TV shows in accessories in HB, but the TV itself never shows up in HK.

**Comment by grzegorz914** [comment]
Was added before or  first new installation. 
Also check the accessory name, if use special characters may be not displayed.
Try to clear cache.

**Comment by siobhanellis** [comment]
It was there, but I started getting the address conflicts. I tried deleting and re-adding, so config is the same.

Clearing the cache. What implications does that have?

Siobhan

IOT: Practical HomeKit: ( https://practicalhomekit.blogspot.com )
Charity Fundraising: Lammie Drive: ( lammiedrive.blogspot.com<http://lammiedrive.blogspot.com/> )


From: Grzegorz ***@***.***>
Date: Wednesday, 10 January 2024 at 12:42
To: grzegorz914/homebridge-lgwebos-tv ***@***.***>
Cc: siobhanellis ***@***.***>, Author ***@***.***>
Subject: Re: [grzegorz914/homebridge-lgwebos-tv] Bridge appears to be paired, but not TV (Issue #196)

Was added before or first new installation.
Also check the accessory name, if use special characters may be not displayed.
Try to clear cache.

**Comment by grzegorz914** [comment]
You can use this method https://github.com/grzegorz914/homebridge-lgwebos-tv/wiki#troubleshooting 
‘to remove only cache from this plugin

**Comment by siobhanellis** [comment]
Done.

thx

Siobhan

IOT: Practical HomeKit: ( https://practicalhomekit.blogspot.com )
Charity Fundraising: Lammie Drive: ( lammiedrive.blogspot.com<http://lammiedrive.blogspot.com/> )


From: Grzegorz ***@***.***>
Date: Wednesday, 10 January 2024 at 17:29
To: grzegorz914/homebridge-lgwebos-tv ***@***.***>
Cc: siobhanellis ***@***.***>, Author ***@***.***>
Subject: Re: [grzegorz914/homebridge-lgwebos-tv] Bridge appears to be paired, but not TV (Issue #196)

You can use this method https://github.com/grzegorz914/homebridge-lgwebos-tv/wiki#troubleshooting
‘to remove only cache from this plugin
