### ISSUE TITLE
configuration problem

### ISSUE THREAD

**Issue by slaw47** [grzegorz914/homebridge-lgwebos-tv#199]
I try to configure the plug-in but still received the message:

[homebridge-lgwebos-tv] Name: OK, host: OK, mac: 78-5D-C8-83-61-7A, in config wrong or missing.

What is wrong?

**Comment by grzegorz914** [comment]
use `:` in Mac Address

**Comment by slaw47** [comment]
Thank you, it is run
Now new message:
[08/02/2024, 18:13:23] [homebridge-lgwebos-tv] Device: 192.168.68.71 LG TV, debug: Channel error: {
  "returnValue": false,
  "errorCode": -1000,
  "errorText": "internal error"

**Comment by grzegorz914** [comment]
Ignore this, probably you have no any tv channel configured.
