### ISSUE TITLE
On/Off switch doesn't work

### ISSUE THREAD

**Issue by Lui5Jacint0** [grzegorz914/homebridge-lgwebos-tv#20]
It´s not possible to turn on/off the TV with the pluggin. Any idea how to fix it?

**Comment by grzegorz914** [comment]
Log please?
Config please?
TV model support Wake-On-LAN?

**Comment by Lui5Jacint0** [comment]
11/05/2020, 11:53:47 [LgWebOsTv] Manufacturer: LG Electronics
11/05/2020, 11:53:47 [LgWebOsTv] Model: 47LB650V-ZN
11/05/2020, 11:53:47 [LgWebOsTv] System: webOS
11/05/2020, 11:53:47 [LgWebOsTv] Serialnumber: 3c:cd:93:9d:f5:68
11/05/2020, 11:53:47 [LgWebOsTv] Firmware: 05.70

On/Off does not appear in log

**Comment by Lui5Jacint0** [comment]
[
    {
        "name": "LG TV",
        "host": "192.168.1.107",
        "mac": "C8:02:10:49:9D:88",
        "volumeControl": false,
        "switchInfoMenu": true,
        "inputs": [
            {
                "name": "Live TV",
                "reference": "com.webos.app.livetv"
            },
            {
                "name": "MEO",
                "reference": "com.webos.app.hdmi1"
            },
            {
                "name": "Chromecast",
                "reference": "com.webos.app.hdmi2"
            },
            {
                "name": "Netflix",
                "reference": "netflix"
            },
            {
                "name": "YouTube",
                "reference": "youtube.leanback.v4"
            },
            {
                "name": "LG Store",
                "reference": "com.webos.app.discovery"
            }
        ]
    }
]

**Comment by grzegorz914** [comment]
Please add to the config:
"supportOldWebOs": true,

**Comment by Lui5Jacint0** [comment]
This works thanks a lot!
