### ISSUE TITLE
Volume sensor is not working as documented

### ISSUE THREAD

**Issue by xus2** [grzegorz914/homebridge-lgwebos-tv#200]
Hello, thanks for the plugin.

In documents sensorVolume says it will create a contact sensor active on every volume change but for me it's always open no matter what on a LG CX. I manually edit the line 341 in lgwebosdevice.js to 
`const state = this.power ? (this.sensorVolumeState !== true) : false;` 
to get the my expected behaviour: toggle on and off on each volume change. 

Am I missing something or is this a bug? Thank you.

**Comment by grzegorz914** [comment]
It’s fixed

**Comment by xus2** [comment]
Thank you. 
Line (343) only loops once so sensor stays open (true).
Changing `i < 1` to `i < 2` fixes the problem.

Also this line (344) causes an error, changing `power` to `this.power` fixed it on my end locally.
`const state = power ? [true, false][i] : false;`
