### ISSUE TITLE
Update offered v2.16.28 → v2.16.0

### ISSUE THREAD

**Issue by epheterson** [grzegorz914/homebridge-lgwebos-tv#201]
I've been noticing the LG plugin offering updates a lot, and today I finally checked the version changes. I think I've been moving forwards and backwards on versions, why would 2.16.28 offer to "update" to 2.16.0?

My update page:
Update: homebridge-lgwebos-tv
v2.16.28 → v2.16.0
Release Notes
Changes
added possibility to disable prefix name for buttons, sensors, picture meodes and sound modes
config schema updated
cleanup
Full Changelog: https://github.com/grzegorz914/homebridge-lgwebos-tv/compare/v2.15.0...v2.16.0

<img width="830" alt="Screenshot 2024-02-18 at 7 43 40 PM" src="https://github.com/grzegorz914/homebridge-lgwebos-tv/assets/151483/def53f8e-3811-4392-a028-127ac79a0422">

**Comment by grzegorz914** [comment]
I don’t now.
