### ISSUE TITLE
Turn on TV via Homekit

### ISSUE THREAD

**Issue by peibol81** [grzegorz914/homebridge-lgwebos-tv#205]
I have an LG OLED G3 TV with native Homekit integration. But when I add it to Homekit I can't turn it on and it appears as 'no response' when it's turned off. If I use this plugin instead of the native integration, are these problems solved? Thank you

**Comment by grzegorz914** [comment]
Use only one integration, or use native integration and disable TV service in plugin.

**Comment by peibol81** [comment]
The TV service is an option of the plugin? I connect TV via ethernet, is required activate wlan or the option of remote turn on by mobile device? ThanksEl 27 mar 2024, a las 5:30, Grzegorz ***@***.***> escribió:﻿
Use only one integration, or use native integration and disable TV service in plugin.

**Comment by grzegorz914** [comment]
TV service can be disabled in plugin config, see readme.

**Comment by peibol81** [comment]
I used only the native integration and I had the problem of turn on/ 9ff.Now my TV is not integrated with Homekit and I want to know if this problem will be solved if I use your plugin.ThanksEl 27 mar 2024, a las 5:30, Grzegorz ***@***.***> escribió:﻿
Use only one integration, or use native integration and disable TV service in plugin.

**Comment by grzegorz914** [comment]
Probably your TV is wrong configured and You can not on/of TV over HomeKit. Check TV settings please. 
https://www.lg.com/au/support/product-help/CT20088015-1437132986635

**Comment by peibol81** [comment]
Thanks for your time.I see the web you send and my TV don’t have the same menus, but appears everything is ok in my tv. I have configured my lg account and lg connect apps and seems all be ok.I see 2 images attached in this mail. I hope you can see the problem. Now the tv is added to homekit (not via your plugin, added via native lg homekit integration).If with your pluginnI can solve this problem, I should use it.ThanksEl 27 mar 2024, a las 7:59, Grzegorz ***@***.***> escribió:﻿
Probably your TV is wrong configured and You can not on/of TV over HomeKit. Check TV settings please.
https://www.lg.com/au/support/product-help/CT20088015-1437132986635
