### ISSUE TITLE
WOL issue

### ISSUE THREAD

**Issue by wwhite74** [grzegorz914/homebridge-lgwebos-tv#207]
I have 2 NICs in my home bridge machine,  both on same network, but different IPs (when it hits the router, one goes out on VPN, one doesn't)  10.1.2.x, 10.1.3.x, both with 255.255.254.0 masks

home bridge is bound to the 10.1.2.x

the 2 is most of my network including the TV.

it was sending magic packet to 10.1.2.255,   I couldn't see it in Wireshark elsewhere on the network. 

I went into the wol.js file and manually changed to send on 255.255.255.255 and now it wakes the TV. 

I had thought maybe it was trying to send a .2 broadcast from the .3 address, but in Wireshark the updated magic packet is coming from the 10.1.2. interface

     // this.ipAddress = host.join('.');
        this.ipAddress = '255.255.255.255';

**Comment by grzegorz914** [comment]
Thanks for the tip
