### ISSUE TITLE
Log from New Homebridge Beta

### ISSUE THREAD

**Issue by donavanbecker** [grzegorz914/homebridge-lgwebos-tv#21]
`
The plugin "homebridge-lgwebos-tv" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!
`

**Comment by grzegorz914** [comment]
Fixed.
