### ISSUE TITLE
Screen Off isn’t real screen off

### ISSUE THREAD

**Issue by qoodanny** [grzegorz914/homebridge-lgwebos-tv#211]
I am using projector, and the light still on from the projector. It is just projecting black instead of make the bulb off

**Comment by grzegorz914** [comment]
May be LG can explain for You why realize this function  this way on projector.
Have You possibility to switch off the bulb with oryginal RC, if yes then get the debug log.

**Comment by qoodanny** [comment]
There is no option to do picture off on any original way
