### ISSUE TITLE
iPhone RC app stopped working on new version

### ISSUE THREAD

**Issue by loic-martinez-freelance** [grzegorz914/homebridge-lgwebos-tv#220]
Hello

Updating the plugin prevent the remote app to work.
Reverting to 2.20.0 fix the issue.

Here is the log message when any button of the remote app is clicked  

[LgWebOsTv] Device: 192.168.1.21 Téléviseur, Specialized socket not connected.

Thanks

**Comment by grzegorz914** [comment]
fixed in 3.1.1
