### ISSUE TITLE
Cannot update plugin

### ISSUE THREAD

**Issue by psycoticninja** [grzegorz914/homebridge-lgwebos-tv#222]
Homebridge tells me there is a new update to this plugin (v3.1.3) but when I attempt to update nothing happens.

I've tried from pressing the update button next to the plugin card and also clicking on Manage Version > changing to v3.1.3 and press install and nothing happens.

I use this plugin and homebridge-meraki-control which you also author and both have this issue (not sure if your other plugins may have the same issue?) 

I have tested with other plugins authored by others and these update just fine.

**Comment by grzegorz914** [comment]
Remove the plugin without config remove and install again.

**Comment by grzegorz914** [comment]
Was Bug

**Comment by psycoticninja** [comment]
I’ve uninstalled the plugin - then installed with v3.1.3 and the child bridge will not start so I can’t add the TV back to HomeKit. 

I’ve rolled back to v3.1.2 which is working.

**Comment by metaljay** [comment]
Just to add, I regularly get a 'update' to downgrade, do I need to uninstall fully and re-do?
<img width="784" alt="Screenshot 2024-09-16 at 2 43 55 PM" src="https://github.com/user-attachments/assets/1c2efa2b-1c70-4032-8217-cfae78b116cd">

**Comment by grzegorz914** [comment]
No, it is only changelog
