### ISSUE TITLE
TV Wont Turn On Homekit

### ISSUE THREAD

**Issue by jeffcohen-ai** [grzegorz914/homebridge-lgwebos-tv#223]
I can't turn the TV on using the plugin and homekit.  I can turn off the TV, change inputs but cannot turn the TV on.

Any suggestions would be great.

**Comment by grzegorz914** [comment]
wrong Mac address in config, local lan problems

**Comment by alvaroledesma** [comment]
Is there a way to designate what network interface this plugin uses? I am having the same issue with being unable to power on the TV and I believe it's because the magic packet is sending from the default interface instead of the secondary one.

**Comment by grzegorz914** [comment]
The magic packet is sent to all interfaces:
https://github.com/grzegorz914/homebridge-lgwebos-tv/blob/767a444d7be1ba1c39feacaa9ef33703d207a2ed/src/wol.js#L11

**Comment by robled** [comment]
I've found that when using Docker macvlan interfaces that the `255.255.255.255` address will not work.  I have to specify the broadcast address for each network interface, e.g. `192.168.50.255`.  Having a configuration option would be helpful for these scenarios.

**Comment by grzegorz914** [comment]
I will add it.

**Comment by grzegorz914** [comment]
Added in v3.3.0
