### ISSUE TITLE
Turn off tv (external integrations)

### ISSUE THREAD

**Issue by ruudvdb** [grzegorz914/homebridge-lgwebos-tv#231]
I've noticed to 'problems':

1. The documentation states you have to send this json in order to power on the tv: {Power: true}, this does not work. The correct parameter is: {"Power": 1} to turn the TV on and {"Power": 0} to turn the TV off.
2. Of the TV is already off and you send a request: {"Power": 0} the TV will turn on instead of staying off.

The last part is not realy a bug in this code base, I think it's an LG API 'bug' but a workaround could be in this code by checking if the TV is already in the OFF-state, if so, don't do anything.

**Comment by grzegorz914** [comment]
fixed
