### ISSUE TITLE
Stuck at "Please accept authorization on TV."

### ISSUE THREAD

**Issue by jeremydvoss** [grzegorz914/homebridge-lgwebos-tv#233]
`[LgWebOsTv] Device: <IP address>  LG WebOS Projector, Please accept authorization on TV.`

I get this message in the logs. Nothing comes up on the projector. There is no documentation that seems to mention this authentication process.

**Comment by grzegorz914** [comment]
This plugin is for TV, I don’t know how to authorize RC for Projector.

**Comment by jeremydvoss** [comment]
What's the process on the tv? I would think it would be the same but LG sucks at keeping their WebOS devices consistent.

**Comment by jeremydvoss** [comment]
It worked! I think I just had to restart homebridge when the projector was on Home so it would be "ready". Unfortunately, the plugin does not work well for me. It consistently this it's "On" when it's "Off" making it impossible to run automation with my projector screen. May switch back to the broadlink plugin since it does better ip address detection.
