### ISSUE TITLE
Cannot read property 'reference' of undefined

### ISSUE THREAD

**Issue by serbasan** [grzegorz914/homebridge-lgwebos-tv#24]
Since 0.93 I have this error and homebridge does not start. I have configured the inputs with "Input type" parameter. I have also deleted all entries. The error is still there

5/14/2020, 10:17:35 AM] Homebridge is running on port 53686.
[5/14/2020, 10:17:36 AM] TypeError: Cannot read property 'reference' of undefined
    at /homebridge/node_modules/homebridge-lgwebos-tv/index.js:295:31
    at Array.forEach (<anonymous>)
    at lgwebosTvDevice.prepareInputsService (/homebridge/node_modules/homebridge-lgwebos-tv/index.js:292:15)
    at lgwebosTvDevice.prepareTelevisionService (/homebridge/node_modules/homebridge-lgwebos-tv/index.js:238:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[5/14/2020, 10:17:36 AM] Got SIGTERM, shutting down Homebridge...
Websocket failed to connect. Is the server running

**Comment by grzegorz914** [comment]
Get Your config Here.

**Comment by serbasan** [comment]
Hi:
        {
            "devices": [
                {
                    "name": "LG TV",
                    "host": "192.168.1.120",
                    "mac": "38:xx:xx:xx:d3:ab",
                    "volumeControl": true,
                    "switchInfoMenu": true,
                    "supportOldWebOs": false,
                    "inputs": [
                        {
                            "name": "AppleTV",
                            "reference": "com.webos.app.hdmi4",
                            "type": "HDMI"
                        },
                        {
                            "name": "Directo",
                            "reference": "com.webos.app.livetv",
                            "type": "TUNER"
                        }
                    ]
                }
            ],
            "platform": "LgWebOsTv"
        }

Thank you very much for your work

**Comment by grzegorz914** [comment]
Correct is:

{
    "platform": "LgWebOsTv",
    "devices": [
        {
            "name": "LG TV",
            "host": "192.168.1.120",
             "mac": "38:xx:xx:xx:d3:ab",
             "volumeControl": true,
             "switchInfoMenu": true,
             "supportOldWebOs": false,
            "inputs": [
                {
                    "name": "HDMI 3",
                    "reference": "com.webos.app.hdmi3"
                },
                {
                    "name": "Apple TV",
                    "reference": "com.webos.app.hdmi4"
                }
            ]
        }
    ]
}

here is updated README: https://github.com/grzegorz914/homebridge-lgwebos-tv#configuration-plugin

**Comment by serbasan** [comment]
I think both settings are correct. The position of "platform": "LgWebOsTv" is correct on both.
Anyway I have changed it and I have deleted all the entries with a basic configuration and I continue with the same error:

        {
            "platform": "LgWebOsTv",
            "devices": [
                {
                    "name": "LG TV",
                    "host": "192.168.1.120",
                    "mac": "38:xx:xx:xx:xx:ab",
                    "volumeControl": true,
                    "switchInfoMenu": false,
                    "supportOldWebOs": false
                }
            ]
        }


[5/14/2020, 11:22:40 AM] Homebridge is running on port 53686.
[5/14/2020, 11:22:41 AM] TypeError: Cannot read property 'reference' of undefined
    at /homebridge/node_modules/homebridge-lgwebos-tv/index.js:295:31
    at Array.forEach (<anonymous>)
    at lgwebosTvDevice.prepareInputsService (/homebridge/node_modules/homebridge-lgwebos-tv/index.js:292:15)
    at lgwebosTvDevice.prepareTelevisionService (/homebridge/node_modules/homebridge-lgwebos-tv/index.js:238:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[5/14/2020, 11:22:41 AM] Got SIGTERM, shutting down Homebridge...

homebridge infinite restart loop. It all started with 0.9X

**Comment by grzegorz914** [comment]
No need this in config, is in code as default input:
```
{
"name": "Directo",
"reference": "com.webos.app.livetv",
"type": "TUNER"
}
```
I do not have any crash, what system U use. ?

**Comment by redtom13** [comment]
Same error here. cleared my config, same error.
TypeError: Cannot read property 'reference' of undefined

at /usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:295:31
May 14 12:27:22 redpi homebridge[3112]:     at Array.forEach (<anonymous>)
May 14 12:27:22 redpi homebridge[3112]:     at lgwebosTvDevice.prepareInputsService (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:292:15)
May 14 12:27:22 redpi homebridge[3112]:     at lgwebosTvDevice.prepareTelevisionService (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:238:8)


"platform": "LgWebOsTv",
		"devices": [
                {
                    "name": "TV",
                    "host": "192.168.100.26",
                    "mac": "04:4e:af:17:14:76",
                    "volumeControl": true,
                    "switchInfoMenu": true,
                    "supportOldWebOs": false

**Comment by serbasan** [comment]
> No necesita esto en la configuración, está en el código como entrada predeterminada:
> 
> ```
> {
> "name": "Directo",
> "reference": "com.webos.app.livetv",
> "type": "TUNER"
> }
> ```
> 
> No tengo ningún bloqueo, qué sistema U utilizo. ?

Linux server with docker and oznu/docker-homebridge and homebridge 1.0.4. Could I have to delete some configuration from version 0.8.X?

**Comment by grzegorz914** [comment]
Best to use settings in Config UI X

**Comment by grzegorz914** [comment]
Start homebridge in debug mode -D and get the log.

**Comment by serbasan** [comment]
I have always use the config UI. I'm back to version 0.8.9 and everything is correct.
I update to 0.9.5 and same problem. With debugging enabled this is the log:

[5/14/2020, 2:10:11 PM] Homebridge is running on port 53686.
[5/14/2020, 2:10:11 PM] [LgWebOsTv] Device: 192.168.1.120 LG TV, connecting...
[5/14/2020, 2:10:12 PM] [LgWebOsTv] prepareTelevisionService
[5/14/2020, 2:10:12 PM] [LgWebOsTv] prepareSpeakerService
[5/14/2020, 2:10:12 PM] [LgWebOsTv] prepareInputsService
[5/14/2020, 2:10:12 PM] [LgWebOsTv] prepareVolumeService
[5/14/2020, 2:10:12 PM] ReferenceError: j is not defined
    at lgwebosTvDevice.prepareVolumeService (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:277:49)
    at lgwebosTvDevice.prepareTelevisionService (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:240:9)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[5/14/2020, 2:10:12 PM] Got SIGTERM, shutting down Homebridge...
[5/14/2020, 2:10:13 PM] [LgWebOsTv] Device: 192.168.1.120 LG TV, error: Error: connect EHOSTUNREACH 192.168.1.120:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.120',
  port: 3000
}

**Comment by grzegorz914** [comment]
> I have always use the config UI. I'm back to version 0.8.9 and everything is correct.
> I update to 0.9.5 and same problem. With debugging enabled this is the log:
> 
> [5/14/2020, 2:10:11 PM] Homebridge is running on port 53686.
> [5/14/2020, 2:10:11 PM] [LgWebOsTv] Device: 192.168.1.120 LG TV, connecting...
> [5/14/2020, 2:10:12 PM] [LgWebOsTv] prepareTelevisionService
> [5/14/2020, 2:10:12 PM] [LgWebOsTv] prepareSpeakerService
> [5/14/2020, 2:10:12 PM] [LgWebOsTv] prepareInputsService
> [5/14/2020, 2:10:12 PM] [LgWebOsTv] prepareVolumeService
> [5/14/2020, 2:10:12 PM] ReferenceError: j is not defined
> at lgwebosTvDevice.prepareVolumeService (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:277:49)
> at lgwebosTvDevice.prepareTelevisionService (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:240:9)
> at listOnTimeout (internal/timers.js:549:17)
> at processTimers (internal/timers.js:492:7)
> [5/14/2020, 2:10:12 PM] Got SIGTERM, shutting down Homebridge...
> [5/14/2020, 2:10:13 PM] [LgWebOsTv] Device: 192.168.1.120 LG TV, error: Error: connect EHOSTUNREACH 192.168.1.120:3000
> at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
> errno: 'EHOSTUNREACH',
> code: 'EHOSTUNREACH',
> syscall: 'connect',
> address: '192.168.1.120',
> port: 3000
> }
Fixed
