### ISSUE TITLE
Can't rename HDMI Ports & Can't delete Live TV

### ISSUE THREAD

**Issue by Endlessknight** [grzegorz914/homebridge-lgwebos-tv#25]
If I rename the HDMI Ports in the home app it will change back to HDMI 1 or 2 or 3 depending on which I have renamed. Also I can't remove Live TV. Some People use a Set-Top-Box so there should be an option to remove "Live TV"

**Comment by grzegorz914** [comment]
Change name it working for me OK, Every TV have Live TV, if U use Sat Receiver U can free to rename one of HDMI input.

**Comment by Endlessknight** [comment]
Yes..every TV has Live TV but not everyone uses it. so an Option to remove it would be nice.

**Comment by grzegorz914** [comment]
Ok,
new version available, U can use all inputs in config, and also remove not needed.

**Comment by Endlessknight** [comment]
okay......so if I put the HDMI 1 & 2 in Config now and give them a dedicated name they show up but Live TV and HDMI 1 and HDMI 2 also show up. 
in older Versions it was more nice when I had the option to configure what I wanted there and not have stuff that I never use

**Comment by grzegorz914** [comment]
It is older version, only types was added.

**Comment by Endlessknight** [comment]
okay....so I'm on 0.9.7
But still Live TV Shows up and I can't change the HDMI Input names in the Home app. After a reboot of Homebridge the new names are gone. how do I remove Live TV?
<img width="374" alt="Bildschirmfoto 2020-05-14 um 16 11 03" src="https://user-images.githubusercontent.com/13972017/81945033-d7eb2d80-95fd-11ea-9ef8-0a57b2592163.png">
![IMG_0142](https://user-images.githubusercontent.com/13972017/81945092-eafdfd80-95fd-11ea-9a1d-f9a5c0363267.PNG)

**Comment by grzegorz914** [comment]
Ok, 
I’m make changes but not publish them😀
0.9.8 online.

**Comment by Endlessknight** [comment]
Thank you! 👍
