### ISSUE TITLE
LG 47LA860v control

### ISSUE THREAD

**Issue by suzdalini7** [grzegorz914/homebridge-lgwebos-tv#27]
Hi! I could to add a TV 47LA860v in the Home, but can't do anything with it: volume control, Power ON/OFF. RC app on iPhone does not see TV

**Comment by grzegorz914** [comment]
Are U connect to the same network as Your TV?

**Comment by suzdalini7** [comment]
Of course/ iPhone, TV and bridge in the same wi-fi network

**Comment by grzegorz914** [comment]
Must be in RC app visible, can U post Your config?

**Comment by suzdalini7** [comment]
{
            "devices": [
                {
                    "name": "LGSuzique",
                    "host": "192.168.1.40",
                    "mac": "xx:xx:xx:xx:xx",
                    "volumeControl": true,
                    "switchInfoMenu": true,
                    "supportOldWebOs": true,
                    "inputs": [
                        {
                            "name": "Live TV",
                            "reference": "com.webos.app.livetv",
                            "type": "TUNER"
                        },
                        {
                            "name": "HDMI 1",
                            "reference": "com.webos.app.hdmi1",
                            "type": "HDMI"
                        },
                        {
                            "name": "HDMI 2",
                            "reference": "com.webos.app.hdmi2",
                            "type": "HDMI"
                        },
                        {
                            "name": "HDMI 3",
                            "reference": "com.webos.app.hdmi3",
                            "type": "HDMI"
                        },
                        {
                            "name": "HDMI 4",
                            "reference": "com.webos.app.hdmi4",
                            "type": "HDMI"
                        },
                        {
                            "name": "Netflix",
                            "reference": "netflix",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "YouTube",
                            "reference": "youtube.leanback.v4",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "LG Store",
                            "reference": "com.webos.app.discovery",
                            "type": "APPLICATION"
                        }
                    ]
                }
            ],
            "platform": "LgWebOsTv"
        }

**Comment by grzegorz914** [comment]
Looks ok, check your local network please.
Are U add this to the HomeKit app?

**Comment by suzdalini7** [comment]
In HomeKit app I see an icon of my TV with ON/OFF button, volume control and Inputs. In router interface I see iPhone, TV and Homebridge in my local network. But as I wrote earlier RC app on iPhone does not see TV and none of the buttons respond in Home app. Maybe problem with OldWebOs support? My TV was released in 2013

**Comment by grzegorz914** [comment]
Old webos support have nothing to do, if U see this in HomeKit app and not in RC app then 99% network problem

**Comment by suzdalini7** [comment]
But in HomeKit App nothing works. I removed my TV from Home app, plugged on LAN cable, changed IP and rename TV in config, re-added it in HomeKit app - nothing has changed. At the same time I can translate YouTube videos to TV via LAN or wi-fi, can watch photos and videos from android or blackberry devices. And finally in my local network works Aqara Hub + ZigBee devices and Yeelight Crystal Pendant Lamp via Homebridge. What else could be the problem?

**Comment by suzdalini7** [comment]
LG TV Plus and LG ThinQ don't work wit my TV, works only old LG TV Remote app. And there is no LG Connect App option in the TV settings

**Comment by grzegorz914** [comment]
I think Your TV is to old for this plugin

**Comment by suzdalini7** [comment]
I think so too. Thank you for your help

**Comment by grzegorz914** [comment]
Are U paired this app with Your TV, after config and add to the HomeKit on tv display prompt with accept connection, are You accept this.
