### ISSUE TITLE
Volume slider

### ISSUE THREAD

**Issue by Salsalove** [grzegorz914/homebridge-lgwebos-tv#3]
Why is the volume slider missing?

**Comment by grzegorz914** [comment]
Is not missing, You can control the volume using hardware button on iPhone after You go to Remote Control app. This plugin does not support legacy control as You think

**Comment by Salsalove** [comment]
@grzegorz914 
mmm...so, you have to change app going to the remote control app...You can add the slider bar like this plugin [https://github.com/merdok/homebridge-webos-tv](url)

**Comment by Salsalove** [comment]
@grzegorz914 

[https://ibb.co/Swj6tsD](url)

**Comment by grzegorz914** [comment]
This is legacy control which this plugin does not support, in future version of HomeKit app will support speaker service and Volume control will be displayed in TV tile, but not yet.
Speaker service is implemented and right now controlled from RC control app same as other RC control functions.

**Comment by Salsalove** [comment]
Ok...👍🏼
