### ISSUE TITLE
Buttons of TV do not appear in working Homebridge

### ISSUE THREAD

**Issue by PMDHA** [grzegorz914/homebridge-lgwebos-tv#36]
I have Homebridge running for several light switches. After installing the lgwebos plugin it appears in the homebridge, but not in homekit. Any idea what I need to do?

**Comment by grzegorz914** [comment]
U need to add it to HomeKit.

**Comment by PMDHA** [comment]
How do I need to do that? Because it don't appear also not after pressing "I don't have a code or cannot scan" 

For Domoticz it works in Homekit

**Comment by PMDHA** [comment]
Any help possible?

**Comment by grzegorz914** [comment]
Change its name, restart homebridge and try add it again.
