### ISSUE TITLE
Inputs: mode setting

### ISSUE THREAD

**Issue by MED1975** [grzegorz914/homebridge-lgwebos-tv#39]
Hi there

What does the new mode setting do to inputs in your plugin?

Thanks for your development of this Homebridge plugin.

**Comment by grzegorz914** [comment]
The new mode will be if U set:
App - TV switch between configured apps and inputs
Live TV - TV switch between configured channels

This is in development and may not working correct right now but if U ca U can test it but firs add to the config.json inputs correct reference for channels.

**Comment by MED1975** [comment]
Hi - I can do some testing later but I don't really use any of the apps on the TV so may not be much help. Can you confirm what setting I should use for switching between HDMI connections? I have set the live TV to the mode for live TV, but it is not clear if the HDMI is an app or also live tv.

Thanks.

**Comment by grzegorz914** [comment]
All inputs and apps are app,
Only channels are Live TV.
inputs example
 https://github.com/grzegorz914/homebridge-lgwebos-tv#configuration-plugin

**Comment by Spanishu** [comment]
Hi
is it normal that the input show only when the TV is connected?

**Comment by grzegorz914** [comment]
No, if U correct configured config.json inputs

**Comment by Spanishu** [comment]
here my config.json
 {
            "platform": "LgWebOsTv",
            "devices": [
                {
                    "name": "LG TV",
                    "host": "XXXXXXXXX",
                    "mac": "XXXXXXXX",
                    "volumeControl": true,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "Live TV",
                            "reference": "com.webos.app.livetv",
                            "type": "TUNER"
                        },
                        {
                            "name": "Netflix",
                            "reference": "netflix",
                            "type": "APPLICATION"
                        }
                    ]
                }
            ]
        }

**Comment by grzegorz914** [comment]
Please add mode to the config if U use latest test release

```
"name": "Netflix",
"reference": "netflix",
"type": "APPLICATION",
"mode":0
```

**Comment by LMNX** [comment]
@grzegorz914 irrelevant to the topic but more fo a useful app references I dug up. Might be useful for someone :)

Spotify - spotify-beehive
Apple TV - com.apple.appletv
Emby (plex knock-off lol) - com.emby.app

**Comment by angyp** [comment]
Plex - cdp-30
