### ISSUE TITLE
Remote Style on Homekit

### ISSUE THREAD

**Issue by Spanishu** [grzegorz914/homebridge-lgwebos-tv#40]
Hi in your description you show a remote style on home kit of the TV
<img width="155" alt="Screenshot 2020-05-26 at 11 21 52" src="https://user-images.githubusercontent.com/46416423/82883787-37710380-9f43-11ea-8e50-a9720a5781fb.png">
Does it work for all LG? And if yes what is the trick to enable it ?

**Comment by grzegorz914** [comment]
Yes it works for all TV, no need any trick
