### ISSUE TITLE
wake on lan error

### ISSUE THREAD

**Issue by elkorleone** [grzegorz914/homebridge-lgwebos-tv#41]
I have the plugin working well but the only problem is the wake on lan
when tv is on I can control all features without problem, even turn off. But I cannot turn on the tv
Log:
[Alexa] PowerController TurnOff 192.168.1.100 39699 undefined Error: connect ECONNREFUSED 192.168.1.100:39699
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.100',
  port: 39699,
  attempts: 1
}

**Comment by grzegorz914** [comment]
are U defined correct MAC address in config?

**Comment by grzegorz914** [comment]
run HB in debug mode and get the log

**Comment by elkorleone** [comment]
Ok, found the problem. I've tried with Alexa and Eve app. Home app works right
Confused why Eve App doesn't show the tv as accessory.
Alexa plugin semms to have probrems with platforms instead of accessories in HB
