### ISSUE TITLE
Add channel input example

### ISSUE THREAD

**Issue by alessiobulfaro** [grzegorz914/homebridge-lgwebos-tv#45]
Please can you add an example where you setup a channel? 
Because I don't understand how to config it.

{
    "name": "Channel 1", 
    "reference": "WHAT?"
    "type": "TUNER"
    "mode": "WHAT?"
}

Thanks for the help

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-lgwebos-tv#configuration-plugin

**Comment by grzegorz914** [comment]
name - some name U can defined
reference -reference for channel switch (look in the console if channel switch)
type - TUNER
mode - Live TV if reference for channel / App if reference for app

**Comment by angyp** [comment]
So whould this be correct for 

[5/28/2020, 11:01:19 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Channel data: {
  returnValue: true,
  channelId: '1_25_13_13_1539_1588_4116',
  physicalNumber: 25,
  isScrambled: false,
  channelTypeName: 'Terrestrial Digital TV',
  isLocked: false,
  dualChannel: [Object],
  isChannelChanged: false,
  channelModeName: 'Terrestrial',
  channelNumber: '13',
  isFineTuned: false,
  channelTypeId: 1,
  isDescrambled: false,
  isSkipped: false,
  isHEVCChannel: false,
  hybridtvType: 'HBBTV',
  isInvisible: false,
  favoriteGroup: null,
  channelName: '10 HD',
  channelModeId: 0,
  signalChannelId: '1539_1588_4116'
}


                        {
                            "name": "10 HD",
                            "reference": "1_25_13_13_1539_1588_4116",
                            "type": "TUNER",
                            "mode": 1
                        }

**Comment by wallacepost** [comment]
how did you get all the channel information? from the log? 
i only getting up & down from the log, even playing app, it doesn't provide any information.
is there sth like a library for those source?


30/05/2020, 12:08:44 am [LgWebOsTv] Device: 192.168.1.180 TV, get current Power state successfull, state: ON
30/05/2020, 12:08:48 am [LgWebOsTv] Device: 192.168.1.180 TV, set new Input successful: LG Store com.webos.app.discovery
30/05/2020, 12:09:03 am [LgWebOsTv] Device: 192.168.1.180 TV, setRemoteKey successful, command: DOWN
30/05/2020, 12:09:04 am [LgWebOsTv] Device: 192.168.1.180 TV, setRemoteKey successful, command: DOWN
30/05/2020, 12:09:04 am [LgWebOsTv] Device: 192.168.1.180 TV, setRemoteKey successful, command: DOWN
30/05/2020, 12:09:06 am [LgWebOsTv] Device: 192.168.1.180 TV, setRemoteKey successful, command: UP
30/05/2020, 12:09:06 am [LgWebOsTv] Device: 192.168.1.180 TV, setRemoteKey successful, command: ENTER

**Comment by grzegorz914** [comment]
if U look in the Readme https://github.com/grzegorz914/homebridge-lgwebos-tv#configuration-plugin then U see that all channel and app informations all stored to the file.

**Comment by wallacepost** [comment]
i hv read Readme many times, but i can't find any detail explaining how you can pull the  "reference"& Mode from any page / library /log...
 sorry, im new to homebridge.

**Comment by grzegorz914** [comment]
All inputs reference and name can be found in: homebridge_directory/lgwebosTv/apps_19216818 where name == title and reference == id

**Comment by angyp** [comment]
@grzegorz914 

Hey, you didn't answer my question in the fourth post. Do I have the channel input setup correctly? If so it doesn't work. It changes the input back to LiveTV but doesn't tune the channel. You just get the channel the tuner was left on.

Thanks, Angus

**Comment by angyp** [comment]
I got channel input working by modifying line 693 of index.js from                                  

me.lgtv.request('ssap://tv/openChannel', { channelNumber: channelRefer
ence });

me.lgtv.request('ssap://tv/openChannel', { channelId: channelRefer
ence });

The only issue is that after the channel is changed the home app report Live TV as the input instead of the channel.

**Comment by grzegorz914** [comment]
OK, will add this.

**Comment by grzegorz914** [comment]
please check 116

**Comment by angyp** [comment]
The extra stuff you did gives me 8*10 HD inputs? Even know my config is

            "devices": [
                {
                    "name": "Lounge Television",
                    "host": "192.168.15.143",
                    "mac": "38:8c:50:**:**:**",
                    "volumeControl": 1,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "Netflix",
                            "reference": "netflix",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "Foxtel",
                            "reference": "com.webos.app.hdmi1",
                            "type": "HDMI",
                            "mode": 0
                        },
                        {
                            "name": "Shield",
                            "reference": "com.webos.app.hdmi2",
                            "type": "HDMI",
                            "mode": 0
                        },
                        {
                            "name": "Plex",
                            "reference": "cdp-30",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "YouTube",
                            "reference": "youtube.leanback.v4",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "Amazon Prime",
                            "reference": "amazon",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "LiveTV",
                            "reference": "com.webos.app.livetv",
                            "type": "TUNER",
                            "mode": 0
                        },
                        {
                            "name": "10 HD",
                            "reference": "1_25_13_13_1539_1588_4116",
                            "type": "TUNER",
                            "mode": 1
                        }
                    ]
                }
            ],
            "platform": "LgWebOsTv"
        }
    ]

**Comment by grzegorz914** [comment]
Chęci 117

**Comment by angyp** [comment]
117 works but has the same issue I had with just my edit

"The only issue is that after the channel is changed the home app reports Live TV as the input instead of the channel"

**Comment by grzegorz914** [comment]
check 118

**Comment by angyp** [comment]
The same thing set input 10 HD and the app reports input Live TV

**Comment by grzegorz914** [comment]
ok 119

**Comment by angyp** [comment]
Nah same issue.

**Comment by grzegorz914** [comment]
finally 0.12.0 working, tested on my TV,s

**Comment by angyp** [comment]
Hi yeah, that works. I think that if the TV is tunned to a channel that is undefined as input then "Live TV" should be returned.

**Comment by grzegorz914** [comment]
If U get LiveTV on first position in config tlen always if input or channel is undefined The LiveTv will be returned

**Comment by angyp** [comment]
Yeah, that doesn't quite work. I have three channels defined as input. If I change the channel to one of the defined channels using the LG TV remote it is reflected in the home app. However, If I change to an undefined channel the home app stays on the last known defined channel instead of showing LiveTV. 

If I close and reopen the home app while on an undefined channel it does show LiveTV as you stated.
