### ISSUE TITLE
Can’t rename the input Name

### ISSUE THREAD

**Issue by wallacepost** [grzegorz914/homebridge-lgwebos-tv#47]
I have renamed the input in HomeKit, but doesn’t save . It was fine last couple days until Today. I updated the app last night.
![7D7BBCCD-AEC5-42E3-B2E5-AE6451C223A6](https://user-images.githubusercontent.com/65918663/83258143-18030080-a1f9-11ea-9d1c-b3da6773addb.png)
![A8DE6E8B-230F-4321-B621-384BDC75E36E](https://user-images.githubusercontent.com/65918663/83258152-1c2f1e00-a1f9-11ea-8ee7-4090d919bc8b.png)

**Comment by grzegorz914** [comment]
I do not see any problem, just tested right now and working OK,

Please post log

**Comment by wallacepost** [comment]
29/05/2020, 9:44:11 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.livetv reference: com.webos.app.livetv
29/05/2020, 9:44:11 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi1 reference: com.webos.app.hdmi1
29/05/2020, 9:44:11 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi2 reference: com.webos.app.hdmi2
29/05/2020, 9:44:11 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.livetv reference: com.webos.app.livetv
29/05/2020, 9:44:11 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi3 reference: com.webos.app.hdmi3
29/05/2020, 9:44:11 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: netflix reference: netflix
29/05/2020, 9:44:11 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: youtube.leanback.v4 reference: youtube.leanback.v4
29/05/2020, 9:44:11 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.discovery reference: com.webos.app.discovery
29/05/2020, 9:44:11 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi1 reference: com.webos.app.hdmi1
29/05/2020, 9:44:11 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi2 reference: com.webos.app.hdmi2
29/05/2020, 9:44:11 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi3 reference: com.webos.app.hdmi3
29/05/2020, 9:44:11 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: netflix reference: netflix
29/05/2020, 9:44:11 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: youtube.leanback.v4 reference: youtube.leanback.v4
29/05/2020, 9:44:11 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.discovery reference: com.webos.app.discovery
29/05/2020, 9:44:13 pm [orbit] Unhandled message received: clear_low_battery
29/05/2020, 9:44:20 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, get current Input successful: com.webos.app.hdmi1 com.webos.app.hdmi1
29/05/2020, 9:44:20 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, get current Power state successfull, state: ON
29/05/2020, 9:44:30 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, get current Input successful: com.webos.app.hdmi1 com.webos.app.hdmi1
29/05/2020, 9:44:30 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, get current Power state successfull, state: ON
29/05/2020, 9:44:38 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, get current Power state successfull, state: ON
29/05/2020, 9:44:38 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, get current Input successful: com.webos.app.hdmi1 com.webos.app.hdmi1
29/05/2020, 9:45:09 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: Fetch TV reference: com.webos.app.hdmi1
29/05/2020, 9:45:14 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hd reference: com.webos.app.hdmi2
29/05/2020, 9:45:24 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: Apple TV reference: com.webos.app.hdmi2
29/05/2020, 9:45:34 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: PS4 reference: com.webos.app.hdmi3
29/05/2020, 9:46:12 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: LG App reference: com.webos.app.discovery
29/05/2020, 9:46:24 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: Live TV reference: com.webos.app.livetv
29/05/2020, 9:46:34 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: YouTube reference: youtube.leanback.v4
29/05/2020, 9:56:30 pm [Belkin WeMo] Wemo Motion Sensor - Motion Sensor: Detected
29/05/2020, 9:56:33 pm [Belkin WeMo] Wemo Motion Sensor - no motion timer started [60 secs]
29/05/2020, 9:57:17 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: netflix reference: netflix
29/05/2020, 9:57:17 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi1 reference: com.webos.app.hdmi1
29/05/2020, 9:57:17 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi1 reference: com.webos.app.hdmi1
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.discovery reference: com.webos.app.discovery
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.discovery reference: com.webos.app.discovery
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.livetv reference: com.webos.app.livetv
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.livetv reference: com.webos.app.livetv
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi3 reference: com.webos.app.hdmi3
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi3 reference: com.webos.app.hdmi3
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi2 reference: com.webos.app.hdmi2
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi2 reference: com.webos.app.hdmi2
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: youtube.leanback.v4 reference: youtube.leanback.v4
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: youtube.leanback.v4 reference: youtube.leanback.v4
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: netflix reference: netflix
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi1 reference: com.webos.app.hdmi1
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi1 reference: com.webos.app.hdmi1
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.discovery reference: com.webos.app.discovery
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.discovery reference: com.webos.app.discovery
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.livetv reference: com.webos.app.livetv
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.livetv reference: com.webos.app.livetv
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi3 reference: com.webos.app.hdmi3
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi3 reference: com.webos.app.hdmi3
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: youtube.leanback.v4 reference: youtube.leanback.v4
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: youtube.leanback.v4 reference: youtube.leanback.v4
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi2 reference: com.webos.app.hdmi2
29/05/2020, 9:57:18 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi2 reference: com.webos.app.hdmi2
29/05/2020, 9:57:26 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi3 reference: com.webos.app.hdmi3
29/05/2020, 9:57:26 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.discovery reference: com.webos.app.discovery
29/05/2020, 9:57:26 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.livetv reference: com.webos.app.livetv
29/05/2020, 9:57:26 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi2 reference: com.webos.app.hdmi2
29/05/2020, 9:57:26 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: com.webos.app.hdmi1 reference: com.webos.app.hdmi1
29/05/2020, 9:57:26 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, new Input name saved successful, name: youtube.leanback.v4 reference: youtube.leanback.v4

**Comment by grzegorz914** [comment]
All ok in the log

**Comment by wallacepost** [comment]
![Screen Shot 2020-05-27 at 1 37 43 am](https://user-images.githubusercontent.com/65918663/83261343-86968d00-a1fe-11ea-8693-21372f9b7201.png)

**Comment by wallacepost** [comment]
I just renamed everything again, it changed back after 5 seconds.


![3C1A7AA9-91BB-4F6B-97B5-5270482AAC4D](https://user-images.githubusercontent.com/65918663/83261594-f0af3200-a1fe-11ea-9d2d-94ef7853b168.png)

![F9916E7A-E2FB-41BA-B77D-88EDAAFDAE31](https://user-images.githubusercontent.com/65918663/83261580-ebea7e00-a1fe-11ea-8e8f-b0ef330686ed.png)

**Comment by grzegorz914** [comment]
Then change this in config.json in inputs.name

**Comment by wallacepost** [comment]
i did it, it doesn't sync

    "switchInfoMenu": true,
        "inputs": [
            {
                "name": "Live TV",
                "reference": "com.webos.app.livetv",
                "type": "TUNER",
                "mode": 0
            },
            {
                "name": "Fetch TV",
                "reference": "com.webos.app.hdmi1",
                "type": "HDMI",
                "mode": 0
            },
            {
                "name": "Apple TV",
                "reference": "com.webos.app.hdmi2",
                "type": "HDMI",
                "mode": 0
            },
            {
                "name": "PS4",
                "reference": "com.webos.app.hdmi3",
                "type": "HDMI",
                "mode": 0
            },
            {
                "name": "Netflix",
                "reference": "netflix",
                "type": "APPLICATION",
                "mode": 0
            },
            {
                "name": "YouTube",
                "reference": "youtube.leanback.v4",
                "type": "APPLICATION",
                "mode": 0
            },
            {
                "name": "LG Store",
                "reference": "com.webos.app.discovery",
                "type": "APPLICATION",
                "mode": 0

**Comment by wallacepost** [comment]
![F4DB5047-E5AA-416F-AF3E-72514CF382EE](https://user-images.githubusercontent.com/65918663/83262291-125ce900-a200-11ea-8b35-30a298ba82f2.jpeg)

**Comment by grzegorz914** [comment]
I don't know what is wrong on Your site, here all working correct.

**Comment by wallacepost** [comment]
all good, i will reinstall it see how it goes, thanks for trying

**Comment by wallacepost** [comment]
after reinstalling the plug in, i can't find it in "add accessory" any more

29/05/2020, 11:20:58 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, state: Online.
29/05/2020, 11:20:58 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, waiting on confirmation...
29/05/2020, 11:20:58 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, connected.
29/05/2020, 11:20:58 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, get current Power state successful: ON
29/05/2020, 11:20:59 pm [LgWebOsTv] Device: 192.168.1.180 LG TV, RC socket connected.
29/05/2020, 11:20:59 pm [LgWebOsTv] -------- LG TV --------
29/05/2020, 11:20:59 pm [LgWebOsTv] Manufacturer: LG Electronics
29/05/2020, 11:20:59 pm [LgWebOsTv] Model: 65UJ634T-TD
29/05/2020, 11:20:59 pm [LgWebOsTv] System: webOSTV 3.5
29/05/2020, 11:20:59 pm [LgWebOsTv] Serialnumber: 78:5d:c8:05:54:8f
29/05/2020, 11:20:59 pm [LgWebOsTv] Firmware: 80.55
29/05/2020, 11:20:59 pm [LgWebOsTv] ----------------------------------

**Comment by grzegorz914** [comment]
change its name restart HB and add it again
