### ISSUE TITLE
Feature Request - Input

### ISSUE THREAD

**Issue by donavanbecker** [grzegorz914/homebridge-lgwebos-tv#5]
Is there away you could implement to have default inputs and then they can possibly be hidden if chosen in the config.schema.json? Just something I thought I would ask?

**Comment by grzegorz914** [comment]
U can just create scene with default input in HomeKit app.

**Comment by donavanbecker** [comment]
Okay, I figured maybe coding basic inputs like HDMI1,HDMI2,HDMI3,Live TV would make it easier. but not big deal.
