### ISSUE TITLE
Can’t control TV at all

### ISSUE THREAD

**Issue by Lui5Jacint0** [grzegorz914/homebridge-lgwebos-tv#52]
Version 0.11.114 and 0.11.115 completely bricked my tv on HomeKit: can’t control inputs, volume, turn off etc.

Log is ok

`07/06/2020, 21:39:11 [LgWebOsTv] Device: 192.168.1.172 LJ's TV LG, get current Power state successful: ON
07/06/2020, 21:39:11 [LgWebOsTv] Device: 192.168.1.172 LJ's TV LG, disconnected.
07/06/2020, 21:39:11 [LgWebOsTv] -------- LJ's TV LG --------
07/06/2020, 21:39:11 [LgWebOsTv] Manufacturer: LG Electronics
07/06/2020, 21:39:11 [LgWebOsTv] Model: homebridge-lgwebos-tv
07/06/2020, 21:39:11 [LgWebOsTv] System: undefined
07/06/2020, 21:39:11 [LgWebOsTv] Serialnumber: SN0000004
07/06/2020, 21:39:11 [LgWebOsTv] Firmware: FW0000004
07/06/2020, 21:39:11 [LgWebOsTv] ----------------------------------
07/06/2020, 21:39:12 LJ's TV LG is running on port 46375.
07/06/2020, 21:39:14 [LgWebOsTv] Device: 192.168.1.172 LJ's TV LG, get current Power state successfull, state: OFF
07/06/2020, 21:39:14 [LgWebOsTv] Device: 192.168.1.172 LJ's TV LG, get current Volume level successful: 0
07/06/2020, 21:40:33 [LgWebOsTv] Device: 192.168.1.172 LJ's TV LG, get current Power state successfull, state: OFF
07/06/2020, 21:40:33 [LgWebOsTv] Device: 192.168.1.172 LJ's TV LG, get current Volume level successful: 0
07/06/2020, 21:40:36 [LgWebOsTv] Device: 192.168.1.172 LJ's TV LG, set new Power state successful: ON
07/06/2020, 21:40:37 [LgWebOsTv] Device: 192.168.1.172 LJ's TV LG, set new Volume level successful: 15
07/06/2020, 21:40:40 [LgWebOsTv] Device: 192.168.1.172 LJ's TV LG, set new Input successful: MEO undefined `

Config:

[
    {
        "name": "LJ's TV LG",
        "host": "111.11111.1.111",
        "mac": "xx:xx:xx:xx",
        "volumeControl": true,
        "switchInfoMenu": true,
        "supportOldWebOs": true,
        "inputs": [
            {
                "name": "Chromecast",
                "reference": "com.webos.app.hdmi2",
                "type": "HDMI"
            },
            {
                "name": "MEO",
                "reference": "com.webos.app.hdmi1",
                "type": "HDMI"
            },
            {
                "name": "YouTube",
                "reference": "youtube.leanback.v4",
                "type": "APPLICATION"
            },
            {
                "name": "Netflix",
                "reference": "netflix",
                "type": "APPLICATION"
            }
        ]
    }
]

**Comment by angyp** [comment]
add mode to the inputs and you should be good.

**Comment by grzegorz914** [comment]
Yes U need add „mode” to The input.
https://github.com/grzegorz914/homebridge-lgwebos-tv#configuration-plugin

**Comment by Lui5Jacint0** [comment]
I’m unable to save config settings.

**Comment by grzegorz914** [comment]
I donT know what is wrong with Your hoobs config.

**Comment by Lui5Jacint0** [comment]
it says "JSON invalid"

**Comment by grzegorz914** [comment]
Then U need to correct configure the config. Post the config Here then we check.

**Comment by Lui5Jacint0** [comment]
Please check issue "TV doesn't Respond to homebridge #53"
