### ISSUE TITLE
siri 

### ISSUE THREAD

**Issue by yohan0** [grzegorz914/homebridge-lgwebos-tv#54]
I can just turn on/off via siri cannot do anything else 
is do only that or ican also up/down the volume ?

**Comment by yohan0** [comment]
up

**Comment by wallacepost** [comment]
hi, 
what else siri support excepted on / off?
cheers

**Comment by grzegorz914** [comment]
Yes, U can control volume up/down if U enable legacy volume control (slider or fan).
