### ISSUE TITLE
Remote behaviour duplicates info button

### ISSUE THREAD

**Issue by dekuwrangler** [grzegorz914/homebridge-lgwebos-tv#55]
The info button on either setting in the config makes the remote apps playback button behave as a second info button. I’ve switched between info and settings which changes the behaviour but the play/pause button still brings up the same menu

**Comment by grzegorz914** [comment]
Still the issue?

**Comment by dekuwrangler** [comment]
I’m having connectivity issues with the remote. I will probably delete the plug-in and re install it tomorrow and report back.

**Comment by dekuwrangler** [comment]
I am trying to wipe the settings and maybe I'm missing something. I delete the config and then the plugin, restart the server and reinstall the plugin. It seems to remember a bunch of settings such as IP and MAC address as well as home app remembering the inputs (I know this as one of them had a typo before reinstalling) How do I make sure to 'clean' install the plugin so I can make sure it's a fresh install?

**Comment by grzegorz914** [comment]
U need remove cache from Homebridge persistence folder.

**Comment by dekuwrangler** [comment]
Hi. I've been trying to remove anything that could be perceived as relating to the plugin and have tried going nuclear on all cache that I can access (still learning with the directory exploring). When using the plugin for the first time I'm still getting the TV name, IP address and MAC address autofilling.

**Comment by dekuwrangler** [comment]
I feel extremely silly. I have re flashed the SD card and the information has yet again come up. This is because it is the default information. I hadn't changed from the default IP address or name and I checked the default MAC address otherwise I would have figured it out... Lesson learned!
