### ISSUE TITLE
TV dosent wake from standby

### ISSUE THREAD

**Issue by jamseyp** [grzegorz914/homebridge-lgwebos-tv#6]
One thing ive noticed is that the TV dosen't work from Standby, otherwise most other features work well

**Comment by grzegorz914** [comment]
Hi,

Power ON is realised over Wake_ON_LAN, important is that U write correct Mac adress in config.
You need to allow "LG Connect Apps" on your TV - http://www.lg.com/uk/support/product-help/CT00008334-1437131798537-others 
This will only working if You TV support Wake_ON_LAN.

**Comment by jamseyp** [comment]
This wasnt this fix, i had to enable Mobile -TV on 

https://support.quanticapps.com/hc/en-us/articles/115005985729-How-to-turn-on-my-LG-Smart-TV-using-the-App-WebOS-

**Comment by grzegorz914** [comment]
What a model TV U have? it’s Wake On LAN?
