### ISSUE TITLE
Input limitations

### ISSUE THREAD

**Issue by 7RDR7** [grzegorz914/homebridge-lgwebos-tv#60]
Plugin seems to only allow 2 TV inputs, then the third input is added as a non-functioning tile.

**Comment by grzegorz914** [comment]
Hmm, the plugin do not use inputs as Tile, its uses TV service and show inputs and apps as a list.
Can U detailed explain what U mean?

**Comment by 7RDR7** [comment]
Thanks for your response. So, when I add inputs, the first two entered are placed in the inputs list box, but the third input creates a tile under “Accessories” within the HomeKit LG device, and not within the inputs box. If I delete the inputs and enter them in any order, the third input is always placed as a tile under accessories. I’m entering HDMI1, Netflix, Amazon. One input and two apps.

**Comment by grzegorz914** [comment]
Please post Your config.json

**Comment by 7RDR7** [comment]
Thanks. Config looked fine based on your Github manual, so I deleted everything, added one input at a time, add to Home, then deleted from Home, added another one, and so on until I got all three to show up. Works now. It didn’t seem to like it if I tried to add all three at once. Thanks for your responses, and really appreciate your efforts on this plugin.
