### ISSUE TITLE
LG Plex app titel and id

### ISSUE THREAD

**Issue by mtjoernelund** [grzegorz914/homebridge-lgwebos-tv#63]
May very well be me who is missing something very obvious, but I cannot find the correct input name and reference (title and id) for the Plex app on my LG. I suspect that it may be down to the fact that the Plex app was not installed on the LG when I first installed this plugin, so the Plex app does not appear in the app list in .homebridge/log webosTV/apps_ file. Is there anyway to force an update of the contents of this file other than deleting the plugin and re-adding?

I am running WebOS 4.0 and latest version of both Homebridge and this plugin.

**Comment by mtjoernelund** [comment]
Ok, found the solution myself. The apps-file does not update with new apps installed. But if you delete the file, a new one will be created with the current set of apps installed. May be worth adding this to the instructions for the plugin.

**Comment by grzegorz914** [comment]
i will update the code to check the apps every TV start

**Comment by charliwest** [comment]
@mtjoernelund did you find the appID? I can't see it even in the debug logs when I open the app. 
`      "vendor": "Plex",
      "largeIcon": "Plex_130x130.png",
      "icon": "http://192.168.178.34:3000/resources/1dab52aeecbc6af060e7ff2e6808d64c4ab0fdaf/Plex_80x80.png",
      "splashBackground": "Plex_Splash.png",
      "title": "Plex",
      "bgImage": "Plex_Splash.png",`

Thats everything I see, am I missing something?

**Comment by grzegorz914** [comment]
What is it, this is not a Homebridge log.

**Comment by charliwest** [comment]
Hi @grzegorz914 So I turned on debug, opened the app on the TV and then downloaded the log. This is the whole section where Plex is mentioned at all

    {
      "defaultWindowType": "card",
      "appsize": 141406,
      "bgColor": "#000000",
      "CPApp": false,
      "systemApp": false,
      "version": "2.2.0",
      "vendor": "Plex",
      "hasPromotion": false,
      "tileSize": "normal",
      "largeIcon": "Plex_130x130.png",
      "lockable": true,
      "transparent": false,
      "icon": "http://192.168.178.34:3000/resources/1dab52aeecbc6af060e7ff2e6808d64c4ab0fdaf/Plex_80x80.png",
      "checkUpdateOnLaunch": true,
      "spinnerOnLaunch": true,
      "handlesRelaunch": false,
      "unmovable": false,
      "id": "cdp-30",
      "inspectable": false,
      "inAppSetting": false,
      "privilegedJail": false,
      "trustLevel": "default",
      "mediumLargeIcon": "11121380745650039_16789827_115x115.png",
      "splashBackground": "Plex_Splash.png",
      "binId": 1006017,
      "title": "Plex",
      "deeplinkingParams": "",
      "visible": true,
      "resolution": "1920x1080",
      "requiredEULA": "generalTerms",
      "noSplashOnLaunch": false,
      "accessibility": {
        "supportsAudioGuidance": false
      },
      "folderPath": "/media/cryptofs/apps/usr/palm/applications/cdp-30",
      "bgImage": "Plex_Splash.png",
      "installTime": 1583346274,
      "type": "web",
      "main": "index.html",
      "iconColor": "#1f1f1f",
      "disableBackHistoryAPI": true,
      "removable": true
    },

**Comment by grzegorz914** [comment]
Get the complete log during switch to PLEX app

**Comment by charliwest** [comment]
OK, please excuse my ignorance, I have Plex in now. I misread something in the instructions and confused them with a different plugin. 
Seems to have bumped Netflix off though so will carry on playing around.
Thanks for the quick response!
