### ISSUE TITLE
Not works on LG 55EG910V

### ISSUE THREAD

**Issue by chuchi2k2** [grzegorz914/homebridge-lgwebos-tv#64]
Model:55EG910V-ZB
This TV has Webos 2.2.3-171 (beehive-biscayne)

The plugin doesn't work on this TV. We also tried to install other plugin (https://github.com/merdok/homebridge-webos-tv) and this works well (but if i downgrade to version 1.9.3).
For your info, this related problem is discussed here: https://github.com/merdok/homebridge-webos-tv/issues/292

Here my config:  (mac and ip hidden)
{
    "bridge": {
        "name": "Homebridge 5C37",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 51188,
        "pin": "526-32-963"
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "TplinkSmarthome",
            "pollingInterval": 5,
            "platform": "TplinkSmarthome"
        },
        {
            "platform": "LgWebOsTv",
            "devices": [
                {
                    "name": "LG TV",
                    "host": "192.168.2.xx",
                    "mac": "xx:xx:xx:xx:xx:xx",
                    "refreshInterval": 5,
                    "volumeControl": 1,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "name": "Netflix",
                            "reference": "netflix",
                            "type": "APPLICATION",
                            "mode": 0
                        }
                    ]
                }
            ]
        }
    ],
    "accessories": []
}

Any idea to work on my TV?

Thanks.

**Comment by grzegorz914** [comment]
Try latest beta
