### ISSUE TITLE
Input buttons don't appear on Homebridge

### ISSUE THREAD

**Issue by neo3** [grzegorz914/homebridge-lgwebos-tv#66]
Hello,

I installed and configured the plugin correctly on my Homebridge, but I can't see the Input buttons on it and as a result it doesn't work on Alexa.

On the iPhone the Inputs appear, but not as separate buttons.
![Screenshot_1](https://user-images.githubusercontent.com/1847148/94349892-685f6300-001f-11eb-8cca-cf79c7a82127.png)

**Comment by grzegorz914** [comment]
U don’t get any input button, this plugin support native televisionService which Config UI X not support tight now, in Home.app U get whel to switch inputs.

**Comment by neo3** [comment]
The homebridge-webos-tv plugin has the option of showing Inputs as buttons.
