### ISSUE TITLE
The volume shows on even after turning off

### ISSUE THREAD

**Issue by CaseyCZ** [grzegorz914/homebridge-lgwebos-tv#70]
The volume shows on even after turning off.
Plugin works but one problem. I don't have this error with another plugin.
![3B836812-439C-4869-B43D-48AE6463A901](https://user-images.githubusercontent.com/25530709/99915186-73beca00-2d02-11eb-9a95-a54cfee1cdee.jpeg)

**Comment by KeshavMadhavan** [comment]
Hey, I was wondering how you got the tv module to show up at all. I can't get it to show up even though I changed volume control from 0 to "slider" in config file

**Comment by grzegorz914** [comment]
Try latest beta

**Comment by grzegorz914** [comment]
Already fixed
