### ISSUE TITLE
My accessory isn't shown here

### ISSUE THREAD

**Issue by aschmidt74** [grzegorz914/homebridge-lgwebos-tv#76]
Following a migration from a raspberry instance of Homebridge to a Synology Docker container all works fine, communication with the TV, all buttons work in the browser - I'm just unable to add the accessory in Homekit, it just doesn't show up.

Once the old instance on the pi is revived, the accessory is visible, add-able, and working.

But how to convince the new insane to present itself to Homekit?

How to check it's presence independently from Homekit?

Help's appreciated!

**Comment by fouquet** [comment]
Did you remove the "old" TV from HomeKit? I had exactly the same problem (migration from Raspberry Pi to Synology Docker). I had to remove the "old" TV from HomeKit before it was available as an accessory on the new Homebridge instance.

**Comment by aschmidt74** [comment]
Hi René! in Homekit I started **a complete clean installation**, by removing the entire old home, and added all the other homebridge items anew. only the LG-TV troubles me, it's aparently not published and not visible as addable accessory.
Though its "backend" in Homebridge works fine, and even further the communication with the TV works in both directions (in Homebridge in a browser, and TV updates (e.g. channel change) to Homebridge)

The only presence of the **old** instance of LGWebOS-TV is in Homebridge on the retired Raspberry, **iff** I start the HB-service.
Then however I can swiftly add it to Homekit (just to delete it afterwards), even though two instances of homebridge are running on two hosts.

I am really wondering, what xactly is neccesary for an homebridge-accessory to be visible/addable in homekit?

**Comment by fouquet** [comment]
OK, I simply migrated by removing the old Homebridge hub from the Home app and forgot the TV entry. Another hunch: maybe your DSM firewall is blocking the necessary ports? Here's a list: https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology#opening-ports--synology. I have those open.

**Comment by aschmidt74** [comment]
The docker container uses DSM's network interface, no mappings, no firewall. Furthermore I'm in the same network.

I'd gladly check this, if I knew which ports/ protocols Homekit uses.

**Comment by grzegorz914** [comment]
Just simple define port for HB and Accessory:

`   ```
"bridge": {
        "name": "Homebridge",
        "username": "AA:BB:CC:DD:EE:FF",
        "manufacturer": "homebridge.io",
        "model": "homebridge",
        "port": 9100,
        "pin": "123-45-678"
    },
    "description": "HomeKit Bridge",
    "ports": {
        "start": 9101,
        "end": 9150,
        "comment": "In this section set the port for Homebridge accessories."
    }
```, `

**Comment by aschmidt74** [comment]
I had my config like this:
```
{
    "bridge": {
        "name": "Homebridge NAS",
        "username": "AA:BB:CC:DD:EE:FF",
        "port": 52177,
        "pin": "031-45-154"
    },
    "description": "MyHome HomeBridged",
...
}
```
and added a `ports` section - to no avail.

Is there a way to get to the bottom of this, and see which accessory listens on which port. Specificly if and where the lgwebos-tv is available?

**Comment by grzegorz914** [comment]
Yes, just add as may example and used accessory port U can see in homebridge log after restart it.

**Comment by aschmidt74** [comment]
the `ports` setting seems to have an effect, as it shows in the `homebridge.log`:
```
[1/11/2021, 4:34:46 AM] Registering platform 'homebridge-webos-tv.webostv'
[1/11/2021, 4:34:46 AM] [webostv] Initializing webostv platform...
[1/11/2021, 4:34:47 AM] [webostv] Init - initializing devices
[1/11/2021, 4:34:47 AM] [webostv] [Monitor] Init - got TV configuration, initializing device with name: Monitor
[1/11/2021, 4:34:47 AM] Monitor 459F is running on port 9101.
[1/11/2021, 4:34:47 AM] Please add [Monitor 459F] manually in Home app. Setup Code: 031-45-154
```

however; in `HomeKit`, when I `Add Accessory`, `I Don't Have a Code or Cannot Scan`, it doesnt appear in the icon list, yet I continue with `My Accessory Isn't Shown Here` and `Enter code...` which is `031-45-154` from above. Leads to the same icon-list without the webostv/Monitor.
I once had the variant where it told me in the last step that I have allready added the bridge. which is true, as it bears the same setup-code `031-45-154`.

seems stalled. what else can I do?

**Comment by grzegorz914** [comment]
In Your log is other **webos** not my **LgWebOS** plugin so I think U just report in wrong place.

**Comment by aschmidt74** [comment]
how embarrassing! `LgWebOsTv` is not `webostv`.
uninstalled the latter and installed the former - and ... **it works**.
sorry for wasting your time.
have a nice day! ;)
