### ISSUE TITLE
Settings button in Plugin Config doesn't read existing Config file

### ISSUE THREAD

**Issue by fcmarriott** [grzegorz914/homebridge-lgwebos-tv#78]
Hello - I followed your example config and entered the 4 HDMI selections and the recommended Netflix and Youtube services. After restarting the the Homebridge, I can see the different Input options. However, if I click on Settings in the Plugin, it only shows the default Netflix Input. 

The Settings should show all previously entered Inputs. 

![image](https://user-images.githubusercontent.com/77662757/106354287-d8228900-6344-11eb-8a17-ec00e05de318.png)

![image](https://user-images.githubusercontent.com/77662757/106354307-02744680-6345-11eb-91ec-2a5880c89d14.png)

I'm using Official Homebridge Raspberry Pi Image (https://www.reddit.com/r/homebridge/comments/g4rw91/official_homebridge_raspberry_pi_image_released/), and the LG TV config can be found as a Platform in the Homebridge Config Editor. 

Happy to help if I can provide more info.

**Comment by grzegorz914** [comment]
Already fixed
