### ISSUE TITLE
Issues add TVs to the Home App

### ISSUE THREAD

**Issue by greztaylor** [grzegorz914/homebridge-lgwebos-tv#85]
Hi, I hope you're well.  I am attempting to make my TV's accessible in the Home app.  I've been using the plugin for months without issues but following a recent plugin update I found my TVs have become unavailable in the Home App.  I removed them and added them back in to the HomeBridge Config UI and whilst they're visible in the Config UI they simply will not add to the Home App.  I have delete my HomeBridge 'Hub' from the Home App on IOS and added the hub once again only to find that other accessories I have added to Homebridge are accessible.  Any suggestions about what I can do to resolve?

**Comment by grzegorz914** [comment]
Are U use this:
https://github.com/grzegorz914/homebridge-lgwebos-tv#homekit-pairing

**Comment by greztaylor** [comment]
Hi, thank you for coming back to me so quickly.  Yes I'm attempting to add the re-TVs individually however they simply do not show in the home app.  They've traditionally worked without issue.  Whats weird is they're showing in the HomeBridge Config UI.

**Comment by grzegorz914** [comment]
Then please clear cashe in HB, try to Rename na,e of TV restart HB and try to add.

**Comment by greztaylor** [comment]
That fixed the issue thank you very much for all your help and hard work. Apologies for the ‘basic’ questions !!!

Graham Taylor
greztaylor@me.com<mailto:greztaylor@me.com>
Mob: 07966 914539<tel:07966%20914539>

Sent from Outlook<https://aka.ms/sdimjr> for iPhone
________________________________
