### ISSUE TITLE
Volume button write Brightness on title

### ISSUE THREAD

**Issue by davidjubaan** [grzegorz914/homebridge-lgwebos-tv#86]
My Volume button refer as brightness, see attachment.
![WhatsApp Image 2021-02-25 at 19 03 45](https://user-images.githubusercontent.com/64629918/109189798-14f36b80-779d-11eb-8b67-124ad96d4e38.jpeg)

**Comment by grzegorz914** [comment]
And?

**Comment by davidjubaan** [comment]
is there a way to write "Volume" on it?

**Comment by grzegorz914** [comment]
No way but You can change this to fan in config.

**Comment by davidjubaan** [comment]
Thanks


👅
Jubaan
David Rainis
CEO and Founder
http://jubaan.ai<http://jubaan.ai/>
Predict the Unpredictable

On 25 Feb 2021, at 19:35, Grzegorz <notifications@github.com> wrote:

﻿

No way but You can change this to fan in config.
