### ISSUE TITLE
Editing GUI in homebridge only shows one input

### ISSUE THREAD

**Issue by LucaMH** [grzegorz914/homebridge-lgwebos-tv#95]
Editing inputs via ui only shows first configured input, but editing in json shows all

Homebridge v1.3.4
homebridge-lgwebos-tv v1.7.66
homebridge-config-ui-x v4.41.0

<img width="508" alt="json" src="https://user-images.githubusercontent.com/22506082/113442551-85bb2280-93f0-11eb-91df-00d21ea91cb0.png">

<img width="531" alt="gui" src="https://user-images.githubusercontent.com/22506082/113442559-894ea980-93f0-11eb-9e01-53818a7d2995.png">

**Comment by grzegorz914** [comment]
checked and all displays correc on my site, stil the problem exist with latest version?

**Comment by LucaMH** [comment]
just checked, yep, still happens

**Comment by PeterAlexander75** [comment]
I'm just setting this up for the first time. If you add an input after initial setup, you might need to remove the TV from homebridge and add it again to pick up a new input.

**Comment by grzegorz914** [comment]
This is Bug in Config-UI-X, I have reported this but not fixed yet.

**Comment by LucaMH** [comment]
> 
> 
> This is Bug in Config-UI-X, I have reported this but not fixed yet.

any news from them?

**Comment by iSteve-O** [comment]
This seems to be an issue with configUI for a lot of plugins that list multiple devices/paramteters (eWeLink for me). On my HB if I just tap the "add (device/input)" button to create a new one it will show up populated with the ones listed in the config, and I have to keep adding until all of the ones listed in the config show up in the UI, and then the next one will be blank to add the new one device or input. It seems to not show all devices by default for some reason (maybe to save memory on old hw or could just be a bug?). Just throwing that out there. It doesn't seem to cause any actual problems. Good luck with a fix!

**Comment by grzegorz914** [comment]
Exactly, this causes no any problems just visual effects.

**Comment by grzegorz914** [comment]
This is fixed in latest beta Config-UI-X v40.5.5-test.5
https://github.com/homebridge/homebridge-config-ui-x/pull/1504
