### ISSUE TITLE
Volume control error

### ISSUE THREAD

**Issue by gunnargestsson** [grzegorz914/homebridge-lgwebos-tv#96]
Hi,

I am using an external amplifier for my TV.

Getting this error in my log.

This plugin generated a warning from the characteristic 'Volume': characteristic was supplied illegal value: number -1 exceeded minimum of 0. See https://git.io/JtMGR for more info.

**Comment by grzegorz914** [comment]
This is only warning not a error, will prevent this in next release.

**Comment by nocturne1** [comment]
Did this warning actually get fixed? I still get it with v2.17.8.
