### ISSUE TITLE
Frequent reconnects trigger additional auth dialog on tv

### ISSUE THREAD

**Issue by jgraessley** [grzegorz914/homebridge-lgwebos-tv#97]
I have an LG OLED65E6P, the lgwebos-tv plugin appears to reconnect frequently trigger additional approval requests on the tv.

**Comment by grzegorz914** [comment]
Permission problem, get Your config here, try to change key file folder.

**Comment by jgraessley** [comment]
After googling for "webos-tv key file folder" I found this:
https://www.reddit.com/r/homebridge/comments/akvuhn/homebridgewebostv_keyfile_setup/

It looks like the UI config doesn't have access to that setting. I've tried adding a "keyFile": entry to the settings. When using an absolute path that is writable by the user the process is running as, it doesn't look like there is any file created and there is no error log - do I need to enable debug logs to see those?

**Comment by grzegorz914** [comment]
key is stored in /var/lib/homebridge/lgwebosTv/key_xxxxxx
look there and check the file.

**Comment by jgraessley** [comment]
I found the lgwebosTv in ~/.homebridge. There is a key file but it's empty.

**Comment by grzegorz914** [comment]
try to remove the key file, restart home bridge and pair connection again

**Comment by jgraessley** [comment]
Weird. Removed the file once, rebooted, still empty. Tried again and now it contains a hex string. Guess it worked this time? Thank you.
